pkg/controller/credentialsrequest/credentialsrequest_controller.go, pkg/controller/internalcontroller/controller.go
Adds custom backoff rate limiter that starts at 2secs instead of default of 5ms
=> Custom RateLimiter for CredentialsRequest controller

manifests/03-cred-openshift-image-registry.yaml
- s3:HeadBucket
- s3:GetObject
- s3:PutObject
- s3:DeleteObject
- s3:ListBucketMultipartUploads
- s3:AbortMultipartUpload
=> adding permissions to upload/download objects

pkg/controller/utils/utils.go
rename/expose existing function so external users (eg installer) can provide their own list of actions to perm-check against
=> allow passing in your own list of actions to perm-check against

config/manager/deployment.yaml, manifests/0000_30_cloud-credential-operator_01_deployment.yaml
Removes CPU limits from pods, soon to be checked by the test in https://github.com/openshift/origin/pull/22095.
Re https://jira.coreos.com/browse/CO-262
=> Remove limits from pods

pkg/controller/secretannotator/secretannotator_controller_test.go, pkg/controller/utils/utils.go
as reported in https://github.com/openshift/installer/issues/1341 , the root aws account is not a valid user to query against with an iam:SimulatePrincipalPolicy call.
detect when the creds are the root creds (ie UserId == account number), print a warning and allow it through.
=> detect using root user

pkg/controller/credentialsrequest/credentialsrequest_controller.go, pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
in an attempt to lessen the number of AWS API calls, if there hasn't been a generation change, and the lastsynctimestamp is less than an hour old, don't attempt to sync.
=> resync credentialsrequests hourly

pkg/controller/credentialsrequest/status.go, pkg/controller/credentialsrequest/status_test.go
CCO does not have any components to upgrade, so the first time we go to
update status and see that our running version has changed, update the
progressing last transition time to indicate something happened.
=> Bug: 1695205 Reset progressing transition time after upgrades.

README.md
=> update docs to reflect that we are now at v1 (not v1beta1)

pkg/controller/credentialsrequest/status.go
Add all CredentialRequests resources to `relatedObjects` so that [must-gather](https://github.com/openshift/must-gather) will gather them.
* `pkg/controller/credentialsrequest/status.go` (`syncOperatorStatus`): Pass the list of CredentialRequests to `buildExpectedRelatedObjects`.
(`buildExpectedRelatedObjects`): Add a parameter for a slice of CredentialRequests.  Add the provided CredentialRequests resources the list of related objects.
=> status: Add CredentialsRequests to relatedObjects

pkg/gcp/client.go
Adds a timeout to calls to the GCP cloud API so that network errors do not freeze the operator.
=> [gcp] set timeout on cloud API calls

pkg/assets/bindata.go
run 'make' on a fresh checkout of CCO, and the generated bindata shows some uncommited changes.
commit these changes.
=> commit changes to bindata

pkg/controller/credentialsrequest/credentialsrequest_controller.go, pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
fix the case where the credRequest has previously been provisioned, but then the secret holding the creds (cr.Spec.SecretRef) has been deleted.
detect this case, and cause a re-reconcile even if the credRequest has recently been synced
add/update test cases
=> in the event that the secret for a CR is missing, re-reconcile

cmd/manager/render.go, pkg/controller/utils/utils.go
When the render process is run during bootstrap, it will check all files in the destination directory (which also contains the install-time manifests) for the CCO ConfigMap that enables/disables the operator.
This should allow an install process where a user can provide their own install-time manifests with the CCO ConfigMap defined to keep CCO from ever running in the cluster. The user-provided ConfigMap will make it into the cluster during the bootstrap stage, so when the in-cluster CCO is installed, it will see the ConfigMap and never attempt to process CredentialsRequests.
=> search through source manifests to determine operator disabled

OWNERS
add staebler to OWNERS. add bugzilla component to OWNERS.
per request from ART, add bugzilla component to OWNERS.
=> add staebler to OWNERS. add bugzilla component to OWNERS.

manifests/05_deployment.yaml
@joelddiaz @abhinavdahiya @dgoodwin 
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1822900
=> BUG 1822900: fix proxy injection

pkg/cmd/render/render.go
Fix regression from #177 
@dgoodwin @joelddiaz @dulek
=> Bug 1823631: fix bootstrap static pod

README.md
Added Azure documentation in README.md
=> Addition of Azure documentation

pkg/operator/credentialsrequest/credentialsrequest_controller.go
Problem: Deleting the credentials request when CCO was disabled did not work
as expected, but the credentials request couldn't be deleted even when CCO was
re-enabled.
Solution: Creating a watch for cloud-credential-operator-config configmap to
monitor when CCO is re-enabled. Once CCO is re-enabled we reconcile all the
credentials request whose DeletionTimestamp is set.
Jira: https://issues.redhat.com/browse/CO-970
=> Fix credentials request cleanup failure after re-enabling CCO

pkg/operator/awspodidentity/controller.go
/assign @joelddiaz @dgoodwin 
fyi @derekwaynecarr 
This PR adds a status handler to the awspodidentity controller so that
1) failures to apply the static resources are reflected in the `ClusterOperator` status
2) the manifests for static assets are collected by must-gather via `relatedObjects`
=> awspodidentity: add status handler

pkg/operator/credentialsrequest/status.go
Sorry this one slipped in previous PR.
/assign @joelddiaz
=> Bug 1868328: CredentialsRequest should be plural

pkg/operator/credentialsrequest/credentialsrequest_controller.go
Previously we were not watching for admin credentials secrets in the 4.5
code stream. (we are in 4.6) This would require a pod restart or
reconcile for some other reason before status would recalculate.
This change backports the exact code in 4.6 and will now immediately
update the condition on any change to an admin credential in the
cluster.
=> Bug 1883412: Update upgradeable condition on admin cred changes.

manifests/00-clusterreader_clusterrole.yaml, manifests/00-crd.yaml, manifests/00-namespace.yaml, manifests/0000_90_cloud-credential-operator_01_prometheusrole.yaml, manifests/0000_90_cloud-credential-operator_02_prometheusrolebinding.yaml, manifests/0000_90_cloud-credential-operator_03_servicemonitor.yaml, manifests/01-cluster-role-binding.yaml, manifests/01-cluster-role.yaml, manifests/01-operator-config.yaml, manifests/01-role-binding.yaml, manifests/01-role.yaml, manifests/01-service.yaml, manifests/01-trusted-ca-configmap.yaml, manifests/02-sa.yaml
This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.
=> Add IBM Cloud managed annotations to CVO manifests

manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
Minor spelling fix for MissingTargetNamespace alert
/assign @joelddiaz 
/cc @akhil-rane
=> Bug 1916081: MissingTargetNamespace message fix

pkg/operator/utils/utils.go
=> Bug 1927925: spell fix user-visible string

docs/ccoctl.md
update ccoctl docs
this PR builds on top of #306
=> Ccoctl docs

docs/ccoctl.md, pkg/cmd/provisioning/aws/create-iam-roles.go
- fixes wrongly generated trust relationship document for iam roles
- fixes public-key-file parameter typo in the documentation
=> Bug 1948628: Fix ccoctl create aws iam-roles command and docs

Dockerfile
xref: https://issues.redhat.com/browse/CCO-88
=> Bug 1949218: build and include ccoctl into image

pkg/cmd/provisioning/aws/create-iam-roles.go, pkg/cmd/provisioning/aws/create_identity_provider.go
fix param init for create-identity-provider
fix param init for create-iam-roles
=> Bug 1949866: use initialization structure for ID provider

pkg/azure/actuator.go, pkg/gcp/actuator/actuator.go
x-ref: https://issues.redhat.com/browse/OCPBUGSM-29141
=> Bug 1960176: Make sure credentials have newly generated azure client secret

go.sum, pkg/operator/controller.go, pkg/operator/loglevel/controller.go, pkg/operator/loglevel/controller_test.go, pkg/operator/loglevel/status.go, pkg/operator/utils/utils.go, vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go, vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go, vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go, vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go, vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go, vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go, vendor/github.com/robfig/cron/.gitignore, vendor/github.com/robfig/cron/.travis.yml, vendor/github.com/robfig/cron/LICENSE, vendor/github.com/robfig/cron/README.md, vendor/github.com/robfig/cron/constantdelay.go, vendor/github.com/robfig/cron/cron.go, vendor/github.com/robfig/cron/doc.go, vendor/github.com/robfig/cron/parser.go, vendor/github.com/robfig/cron/spec.go, vendor/modules.txt
Add loglevelcontroller to reconcile on changes to CloudCredential object
Change the loglevel on CR updates
Add openshift/library-go vendor modules (operator/loglevel)
=> Bug 1991770: The logLevel and operatorLogLevel values do not work with Cloud Credential Operator

pkg/cmd/provisioning/ibmcloud/create_service_id.go, pkg/cmd/provisioning/ibmcloud/create_service_id_test.go, pkg/cmd/provisioning/ibmcloud/delete_service_id.go, pkg/cmd/provisioning/ibmcloud/ibmcloud.go, pkg/cmd/provisioning/ibmcloud/service_id.go
Implementation of `ccoctl ibmcloud delete-service-id`
=> ibmcloud delete-service-id command

pkg/cmd/provisioning/ibmcloud/create_service_id_test.go, pkg/cmd/provisioning/ibmcloud/delete_service_id_test.go
Add the Unit testscases for the `ccoctl ibmcloud delete-service-id` command
=> Add UT for the delete-service-id command

pkg/cmd/provisioning/aws/create-iam-roles.go
No longer treat CredentialsRequests without spec.serviceAccountNames
filled out as valid. This creates IAM Roles that limit the Role by
audience which means any ServiceAccount in the cluster could potentially
assume the IAM Role (because they all share the same audience).
All CredentialsRequests now populate the ServiceAccountNames field, so
we can remove this transitional support.
xref: https://issues.redhat.com/browse/CCO-104
=> require spec.serviceAccountNames

pkg/gcp/actuator/actuator.go
A nil check was redundant (there was no way for the var to be nil) but done after the pointer in question would have already been dereferenced. Move it to right after the assignment, to guard against a future where it *is* possible to be nil.
[CCO-95](https://issues.redhat.com/browse/CCO-95)
=> Defensive nil check in gcp actuator

manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
As requested in the alerting consistency enhancement
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md,
update the prometheus alerts in the repo to add summary and description
annotations to each alert.
Manual cherry-pick/backport of #395
=> [release-4.9] Bug 1992563: update alerts with summary and descriptions

docs/ccoctl.md, pkg/alibabacloud/client.go, pkg/alibabacloud/mock/client_generated.go, pkg/cmd/provisioning/alibabacloud/create-ram-users.go, pkg/cmd/provisioning/alibabacloud/delete-ram-users.go, pkg/cmd/provisioning/alibabacloud/delete-ram-users_test.go
Alibaba Cloud: support not required input credentials-requests-dir in command delete-ram-users
Fixes #437
=> Bug 2037903: Alibaba Cloud not required credReqDir in command delete-ram-users

docs/ccoctl.md, pkg/cmd/provisioning/nutanix/create_shared_secrets.go, pkg/cmd/provisioning/nutanix/nutanix.go
Change the ccoctl generated nutanix-credentials secret data format. 
Make the nutanix-credentials data format extensible.
x-ref: https://issues.redhat.com/browse/CCO-108
=> Change the ccoctl generated nutanix-credentials secret data format

README.md, docs/ccoctl.md, docs/gcp_workload_identity.md, docs/mode-manual-creds.md, docs/sts.md
One content update for newer `oc adm release extract` syntax.
Added TOCs.
Otherwise mostly typographic stuff.
=> Minor doc updates

pkg/operator/status/status_controller.go, pkg/operator/status/status_controller_test.go
Sorting status arrays to avoid un-needed updates.
Signed-off-by: ehila <ehila@redhat.com>
=> TRT-481: fix: order conditions by type to limit un-needed updates

pkg/cmd/provisioning/constants.go
This was added in
https://github.com/openshift/cluster-version-operator/pull/821 to allow
more featuresets and allow for a future migration to include actual gates
/cc @wking
=> update to release.openshift.io/feature-set to match OCP 4.12

.ci-operator.yaml, Dockerfile, pkg/assets/bootstrap/bindata.go, pkg/assets/v410_00_assets/bindata.go, pkg/aws/actuator/actuator.go, pkg/cmd/provisioning/alibabacloud/create-ram-users.go, pkg/cmd/provisioning/alibabacloud/delete-ram-users.go, pkg/cmd/provisioning/alibabacloud/utils.go, pkg/gcp/actuator/actuator.go, pkg/kubevirt/actuator.go, pkg/openstack/actuator.go, pkg/openstack/utils.go, pkg/operator/credentialsrequest/actuator/actuator.go, pkg/operator/utils/utils.go, pkg/ovirt/actuator.go, pkg/vsphere/actuator/actuator.go
Fixes `verify` and carries the change from #493
=> Changes generated from make update-gofmt with go-1.19.

go.mod
...following ART bot bump via #534 / 61225d546
=> Bump to go 1.20 in go.mod

manifests/01-operator-config.yaml, manifests/01-service.yaml, manifests/04-cluster-operator.yaml
This reverts commit a537936f1fbbb116d84f2e297b18f51c8eef58b3, reversing changes made to 7225227b00e3212a16ef01a170d44465cc588d19.
We are going to enable this on HCP, so we revert the disable PR.
=> Revert "Merge pull request #398 from csrwng/exclude_config_ibmcloud"

manifests/01-service.yaml, manifests/04-cluster-operator.yaml
This reverts commit 3b4d1e2edc904c9215e69d0002c29bbed4d7bf62.
=> Revert "manifests: manually amend resources that get laid down by CVO in HCP"

pkg/cmd/provisioning/azure/create_managed_identities.go
Replication delay has exceeded the current 2 minute timeout frequently with the addition of more custom roles created via CredentialsRequests. This change doubles the current timeout, increasing the timeout to 4 minutes.
=> OCPBUGS-17719: Double timeout delays for managed identity creation and role assignment from 2 to 4 minutes.

.snyk
...as we expect vulns in deps to be caught by the dep scan.
=> snyk: exclude vendor/

pkg/gcp/actuator/policy.go
Prior to this change, when the root credential was removed while the cluster was in mint mode, the cloud credentail operator would become degraded after aproximately an hour. This is because when checking if the service account needed to be updated, it mistakenly considered the custom role to be an excessive role that needed to be removed. Then, it would fail to perform the updates due to missing the root credential.
This change ensures the custom role is considred when checking if the service accounts need to be updated. As a result, the update is no longer happening in this scenario, thus avoiding the need for a root credential.
=> OCPBUGS-28787: gcp actuator update check to consider custom roles

pkg/cmd/provisioning/azure/create_managed_identities.go
xref: OCPBUGS-25193
/assign @jstuever 
/hold 
holding for QE validation
=> OCPBUGS-25193: Scope networkResourceGroup permissions to more operators

docs/azure_workload_identity.md
xref: OCPBUGS-32948
/assign @jstuever
=> OCPBUGS-32948: Update documentation to restart pods when enabling workload identity

pkg/apis/cloudcredential/v1/types_gcp.go, pkg/gcp/actuator/actuator.go
/hold
/assign @jstuever 
xref: [CCO-572](https://issues.redhat.com//browse/CCO-572)
=> CCO-572: STS OLM for GCP (WIF)

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml, bindata/v4.1.0/azure-pod-identity-webhook/deployment.yaml, manifests/03-deployment.yaml, pkg/assets/v410_00_assets/bindata.go
[OCPBUGS-37461](https://issues.redhat.com/browse/OCPBUGS-37461)
Cherry-pick of #681
=> [release-4.15] OCPBUGS-37461: Set required-scc for openshift workloads

pkg/gcp/actuator/actuator.go
=> OCPBUGS-38951: Follow-up bug fixes for CCO-572

go.mod, go.sum, vendor/github.com/sirupsen/logrus/README.md, vendor/github.com/sirupsen/logrus/writer.go, vendor/modules.txt
github.com/sirupsen/logrus v1.9.3
=> OCPBUGS-43335: Update github.com/sirupsen/logrus v1.9.3

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml, pkg/assets/v410_00_assets/bindata.go, pkg/operator/podidentity/awspodidentitywebhook.go, pkg/operator/podidentity/azurepodidentitywebhook.go, pkg/operator/podidentity/podidentitywebhook_controller.go, pkg/operator/podidentity/podidentitywebhook_controller_test.go
=> [release-4.16] OCPBUGS-45939: Add AWS region to aws-pod-identity-webhook

README.md
for users who want to build from source.
=> NO-JIRA: add example of how to build from source

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v5/README.md, vendor/github.com/golang-jwt/jwt/v5/SECURITY.md, vendor/github.com/golang-jwt/jwt/v5/parser.go, vendor/github.com/golang-jwt/jwt/v5/token.go, vendor/modules.txt
github.com/golang-jwt/jwt/v4 v4.5.2
github.com/golang-jwt/jwt/v5 v5.2.2
=> OCPBUGS-53822: update github.com/golang-jwt/jwt

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v5/README.md, vendor/github.com/golang-jwt/jwt/v5/SECURITY.md, vendor/github.com/golang-jwt/jwt/v5/parser.go, vendor/github.com/golang-jwt/jwt/v5/token.go, vendor/modules.txt
github.com/golang-jwt/jwt/v4 v4.5.2
github.com/golang-jwt/jwt/v5 v5.2.2
=> OCPBUGS-53818: update github.com/golang-jwt/jwt

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v5/README.md, vendor/github.com/golang-jwt/jwt/v5/SECURITY.md, vendor/github.com/golang-jwt/jwt/v5/parser.go, vendor/github.com/golang-jwt/jwt/v5/token.go, vendor/modules.txt
github.com/golang-jwt/jwt/v4 v4.5.2
github.com/golang-jwt/jwt/v5 v5.2.2
=> OCPBUGS-53819: update github.com/golang-jwt/jwt

pkg/cmd/render/render.go
This reverts commit 8ff60a024ed9b9889d80ad2745181a1e4bc5c281, reversing changes made to d66761c098427c1a700d984c78d03f785d233d83.
=> OCPBUGS-55204: Revert "Merge pull request #848 from jstuever/OCPBUGS-53429"
