openshift/cloud-credential-operator

Makefile

This solves CI problems where mockgen is not available, but we don't
really care about generating code, we just want to use what's committed.

Add build/test make targets that do not require generation.

---

Dockerfile

Breaking builds, and not necessary for building the image.

Drop unused go get in Dockerfile.

---

manifests/03-cred-openshift-image-registry.yaml

The image registry operator requires additional S3 permissions to function correctly:
- s3:PutBucketTagging
- s3:GetBucketTagging
- s3:PutEncryptionConfiguration
- s3:GetEncryptionConfiguration
- s3:PutLifecycleConfiguration
- s3:GetLifecycleConfiguration
- s3:GetBucketLocation
- s3:ListBucket

Add additional S3 permissions for the Image Registry Operator

---

pkg/aws/actuator/actuator.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go

Most of this merged in a past PR, now we finish the feature and add
testing.

Complete support for adding install config user tags to users in AWS.

---

manifests/03-cred-openshift-ingress.yaml

Move the `cloud-credentials` secret from the operand namespace (`openshift-ingress`) to the operator namespace (`openshift-ingress-operator`): The operator already has permission to read secrets in its own namespace, but not from its operands', and the `cloud-credentials` secret is an input to the operator, not an operand, so having the secret in the operator's namespace simplifies RBAC and is more consistent with how we place other resources related to the operator.
Refine the set of permissions for cluster-ingress-operator: The operator needs to be able to look up Route 53 zones using the `ListHostedZones` and `GetResources` APIs, list load balancers using `DescribeLoadBalancers`, update hosted zones using the `ChangeResourceRecordSets` API, and nothing else.
This PR is related to …

openshift-ingress: Change namespace and permissions

---

pkg/aws/actuator/actuator.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go

Attempted hotloop fix. These controller refs are not namespaced, but
link to a controller (the CredentialsRequest) in another namespace. This
appeared to work fine for cleanup etc, but I suspect it may be the cause
of the post-upgrade hotloop where the controller constantly reconciles
and creates, then re-syncs and sees no secret.
Instead we will delete the target secrets on CredentialsRequest deletion
ourselves.

Remove secret controller refs.

---

config/manager/deployment.yaml
pkg/controller/controller.go

QE hit an oom during controller startup in https://bugzilla.redhat.com/show_bug.cgi?id=1670833, I suspect due to quite a few namespaces.

Fix OOM by increasing memory limits for controller.

---

config/crds/cloudcredential_v1beta1_credentialsrequest.yaml
manifests/0000_30_cloud-credential-operator_00_crd.yaml
pkg/apis/cloudcredential/v1beta1/credentialsrequest_types.go
pkg/aws/actuator/actuator.go
pkg/controller/credentialsrequest/actuator/actuator.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/utils/utils.go

move actuator logic into the actuator code (and reuse existing functionality where it makes sense)
create ActuatorError to allow passing specific error conditions back to the credentialsrequest controller (to allow setting specific Conditions as needed)
allow status.conditions to be empty (nothing wrong with everything healthy)
add GetUserPolicy to list of aws actions needed for the actuator in mint-mode
unrelated deployment requests/limits (from make generate)

refactor credentialsrequest controller

---

pkg/controller/utils/utils.go

This slipped in with b46a3f86 (#8).

pkg/controller/utils: Fix "reutrn" -> "return" comment typo

---

pkg/aws/client.go

An example for include version information is `terraform-provider-aws` [1]
[1]: https://github.com/terraform-providers/terraform-provider-aws/blob/98f11aecb078d82fd7d9b59e5307874797d8f359/aws/config.go#L420

aws: include operator version in UserAgent for AWS API calls

---

Dockerfile

Remove hardcoded amd64 for multi-arch builds.

Remove hardcoded amd64 for multi-arch

---

pkg/aws/actuator/actuator.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/utils/utils.go

The installer recently added Infrastructure.Status.InfrastructureName,
and installer created objects are created with the tag
k8s.io/cluster/infraName=owned.
Update to match, but because beta3 went out without this change,
we want to support upgrades but InfrastructureName would be unset
there. To handle this the operator will fall back to the legacy
openshiftClusterID, which the deprovision code still cleans up.

Update tagging to match newest scheme via installer.

---

pkg/apis/cloudcredential/v1/codec.go
pkg/aws/actuator/actuator.go
pkg/controller/utils/utils.go

AWSProviderCodec is currently only usable in the AWS actuator even
though other cloud providers could make use of the provided
functionality.
This change replaces AWSProviderCodec with ProviderCodec that can be
used with different cloud provider spec and status implementations.
ProviderCodec uses a similar approach to the controller-runtime client
interfaces by writing to the `out runtime.Object` instead of returning a
separate value.
The upcoming PR for the azure actuator will depend on ProviderCodec.

Make AWSProviderCodec generic for other clouds

---

manifests/0000_30_cloud-credential-operator_01_deployment.yaml

When pods fail, you normally get logs, but if other bits of the cluster fail they aren't always available.  This provides a snippet on crashes.

provide pod logs via API on failures

---

manifests/0000_30_cloud-credential-operator_00_clusterreader_clusterrole.yaml

Adds permissions to non-sensitive API resources for cluster-reader.
The general rule is that they can read all non-escalating resources, so not things like secrets, oauthtokens.

add cluster-reader role to aggregate

---

config/manager/deployment.yaml
manifests/0000_30_cloud-credential-operator_01_deployment.yaml

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add node-selector annotation to namespace

---

pkg/azure/passthrough.go
pkg/azure/passthrough_test.go
pkg/controller/secretannotator/secretannotator_controller.go

The root azure credential has more information about the identity
context that is needed for the ingress operator.

Populate all of the azure credential secret

---

pkg/azure/actuator.go
pkg/azure/client.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/status_test.go

- Currently azure actuator doesnt startup, due to suspicion of uninitialized client.
- Initialize the actuator first and validate mode on each request.
Currently only azure specs are present in the cluster might need to change other operators to put valid requests based on platform

Do not look for root creds during startup, instead validate for each request

---

config/manager/deployment.yaml
manifests/01_deployment.yaml

In 4.1, we have taint-based evictions enabled.  This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a `Ready` condition of `False` or `Unknown` after a pod eviction timeout set by the `--pod-eviction-timeout flag` on the kube-controller-manager.  This setting applied to all pods cluster-wide.  The default was `5m`.
With taint-based evictions, all the node lifecycle controller does is taint the node with `node.kubernetes.io/unreachable` and/or `node.kubernetes.io/not-ready` taint with `NoExecute` effect.  This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. …

Fix tolerations

---

pkg/aws/actuator/actuator.go
pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/azure/base.go
pkg/azure/client.go
pkg/azure/const.go
pkg/azure/passthrough.go
pkg/azure/passthrough_test.go
pkg/azure/secret.go
pkg/controller/controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/platform/platform.go
pkg/controller/secretannotator/aws/reconciler.go
pkg/controller/secretannotator/aws/reconciler_test.go
pkg/controller/secretannotator/azure/reconciler.go
pkg/controller/secretannotator/azure/reconciler_test.go
pkg/controller/secretannotator/constants/const.go
pkg/controller/secretannotator/secretannotator_controller.go
pkg/controller/utils/platform.go

The current azure passthrough setup forgot to implement the `secretannotator` for azure. 
As a result, no credentials where ever delivered in response to a credential request.
To resolve that : 
- added the azure implementation for the secret-annotator
- moved aws in its own package `pkg/controller/secretannotator/aws`
- added `pkg/controller/secretannotator/azure`
- made `pkg/controller/secretannotator/controller.go` decide on which implementation to run depending on the platform
to make this refactoring possible, some parts had to move around :
- added `pkg/controller/platform` that retrieves the `platformtype` from a `Manager`
- added a `pkg/controller/secretannotator/constants` package to make it possible to share variables across the different packages without circular dependencies
- …

Azure secret annotator

---

config/manager/deployment.yaml

CCO found to crash loop on clusters with 2000+ namespaces. Remove this
arbitrary restriction.

Drop memory limits on operator deployment.

---

.gitignore
Makefile
manifests/01_deployment.yaml

remove the memory limit as originally intented in #68.
the deployment yaml changes are a no-op. just changes the order of the keys.
update the location where we copy the crd to (match the current filenames in manifets/*).
update gitignore to cover vscode directories.

generate deployment and crd into the right filename

---

pkg/aws/actuator/actuator.go
pkg/aws/client.go
pkg/aws/utils.go
pkg/controller/secretannotator/aws/reconciler.go
pkg/controller/utils/utils.go

Right now, the installer imports the following packages:
```go
ccaws "github.com/openshift/cloud-credential-operator/pkg/aws"
credvalidator "github.com/openshift/cloud-credential-operator/pkg/controller/utils"
```
Disadvantage of the current layout in `cloud-controller-operator` repo causes
`sigs.k8s.io/controller-runtime/pkg/client` package to be imported as well.
The newer version of `sigs.k8s.io/controller-runtime/pkg/client` package requires new
data type(s) from `k8s.io/apimachinery` which are not available in k8s 1.12 (which
is currently imported by the installer).
Also most of the exported methods/functions were used solely by aws part
of the cloud-controller-operator. Moving aws specific bits under pkg/aws
improves importability by other projects and removes the need
for importing …

Separate packages imported by installer from packages importing controller-runtime client

---

.gitignore
Makefile
config/manager/deployment.yaml
manifests/01_deployment.yaml

Backport two commits to drop the memory limits on the cred operator pods:
9e492ed1565900c559c203618eda274e5caf13ff
f19a108f3585806f24c04ca72275f214bcd217e6
This prevents OOMs in large clusters with a lot of namespaces or secrets.

Bug 1723892: Backport removal of memory restrictions for cred operator.

---

manifests/10_cluster-operator.yaml

This should prevent scenarios where the CVO proceeds without waiting for
the cred operator to report success.

Bug 1726451: Add clusteroperator version level gate.

---

Makefile

gosec does static code analysis and checks for common security issues in golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile.

Introduce gocheck for security checks

---

pkg/apis/cloudcredential/v1/credentialsrequest_types.go
pkg/controller/controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_gcp_test.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/credentialsrequest/status.go
pkg/controller/credentialsrequest/status_test.go
pkg/controller/utils/utils.go

currently COO will go down a codepath for CredentialsRequest objects that are intended for a different cloud such that the Status.Provisioned will show True even though the credrequest was ignored.
fix up the credentialsrequest controller to actively ignore credentialsrequests for different cloud platforms than the one the cluster has been deployed to.
update the status calculation to also ignore the invalid credentialsrequests objects when reporting the cluster operator status.
TODO: add condition to credRequests for other clouds/platforms
this PR builds on top of #77

ignore credentialsRequests for other clouds

---

pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_gcp_test.go
pkg/controller/utils/gcp/utils.go
pkg/controller/utils/gcp/utils_test.go
pkg/gcp/actuator/actuator.go
pkg/gcp/actuator/policy.go
pkg/gcp/actuator/role.go
pkg/gcp/actuator/utils.go

Note that passthrough mode is handled differently than in AWS. In AWS we work with a static list of permissions that are needed for the cluster to run with. For GCP passthrough mode, the decision on whether we can satisfy a CredentialsRequest is dynamic. All we absolutely need for passthrough mode is the ability to list service APIs (to determine whether any particular service API is enabled), the ability to get the details for a specific role (so we can determine whether the role exists and the permissions attached to that role), and the ability to get the details of a project (so we can get the project number for a given project name). All the other permissions attached to the root creds in passthrough mode would pass/fail a permissions check during the TestIamPermissions() calls.

implement GCP passthrough mode (and add service API checks)

---

manifests/10_cluster-operator.yaml

This reverts commit 4e137365484bdc5ea86ee5b0cac2fe60b3d3d36c.
We're seeing increased error rates as a result of this change. It is likely the upgrade bug we've seen in the wild but cannot reproduce, only now blocking upgrade because of the level gate. We suspect this was caused by the lack of leader election, but we did not backport leader election along with this change. We will try again next week with both changes.

Revert "Bug 1726451: Add clusteroperator version level gate."

---

pkg/controller/credentialsrequest/status.go
pkg/controller/credentialsrequest/status_test.go

operators should report upgradeability. add upgradeable status when calculating clusteroperator status
addresses BZ https://bugzilla.redhat.com/show_bug.cgi?id=1727012

Bug 1727012: add upgradeable condition unconditionally

---

pkg/controller/secretannotator/gcp/reconciler.go
pkg/gcp/actuator/actuator.go

Matches root creds secret name and key to what the installer lays down:
https://github.com/openshift/installer/blob/e597acb90ffde7a521450750d57ec5554f73c752/data/data/manifests/openshift/cloud-creds-secret.yaml.template#L10

gcp: match secret name/key to installer manifest

---

pkg/apis/cloudcredential/v1/gcp_types.go
pkg/gcp/actuator/actuator.go

Introduces support for the GCP_SKIP_SERVICE_CHECK environment variable
and makes it default to "true" for the operator deployment.

[gcp] Allow skipping service checks

---

pkg/controller/utils/gcp/utils.go
pkg/controller/utils/gcp/utils_test.go

The call to check available permissions only allows 100 permissions at a
time per check. This change splits the call into multiple calls when
there are more than 100 permissions to check.

Split call to check permissions into chunks

---

pkg/aws/actuator/actuator.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go

Our IAM root user has a permission boundary set. This means, every IAM user created by that root user has to have the permission boundary set.
We experienced failure in the installation of Openshift 4 on AWS because the user object to be created fails to pull the permission boundary of the provided user that is used to do the installation.

Bug 1729021: utilize the permissionBoundary of the current user if available

---

pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/credentialsrequest/status.go

don't allow a credentialsRequest that is being ignored to put cloud-cred-operator in a degraded state.
clear other conditions when marking a credentialsRequest as ignored.

Bug 1742753: clear other conditions when ignoring a cred request

---

manifests/01_deployment.yaml
pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/azure/passthrough_test.go
pkg/azure/resourceid.go
pkg/azure/resourceid_test.go

cluster-ingress-operator updates the records in the public DNS zone that is used by the cluster, hence separate from the resource group created for the cluster.
The DNS or dnses.config.openshift.io/v1 object's `.spec.publicZone` is optional, and when set the, resource-group from the ID will be used.
The current api doesn't allow scoping permissions to a single resource, therefore, the permissions are provided to the entire resource group.
Also adds a resourceid helper to find the resource group for the public zone ID.

Bug 1743728: pkg/azure: also provide operators access to the resource group containing public DNS zone

---

pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/azure/minter.go
pkg/azure/passthrough_test.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/status_test.go

Azure Application Registrations exist outside of a Resource Group and are not taggable. In order to allow a mechanism for the OpenShift installer/uninstaller to more fully clean up a cluster during deprovisioning, track any created App Registrations by tagging the App Registration's Service Principal (which is taggable). The App Registration ID (needed for full cleanup), can be found in the Service Principal's 'appId' field.
Service Principals tags are just strings (not key=value pairs), so tag the Service Principal with 'kubernetes.io_cluster.[cluster infra name]=owned' (to closely follow the pattern where key, values are supported).
Also, update test cases to more clearly indicate the expected Azure API calls for each test case.

tag Service Principals on create

---

pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/controller/utils/utils.go
pkg/controller/utils/utils_test.go
pkg/gcp/actuator/actuator.go
pkg/gcp/actuator/utils.go

Azure allows a 93 character service principal name. Preserve the entire 32 character infraID (max length from the installer) and leave 54 characters for the credentialsRequest name, and a final 5 chars for randomness (all fields separated by dashes).

allow 32 char infraID in generated Service Principal names

---

pkg/aws/client.go
pkg/aws/mock/client_generated.go
pkg/aws/utils.go
pkg/controller/secretannotator/aws/reconciler_test.go

handle the posibilitiy of paginated results from SimulatePrincipalPolicy

---

Makefile

remove unused docker pieces
and allow buildah to use the default auth from /run/user/UID/containers/auth.json

allow for non-sudo builds on Fedora

---

pkg/controller/add_configmap.go
pkg/controller/configmap/configmap_controller.go
pkg/controller/configmap/configmap_controller_test.go

in order to have the pod run with an up-to-date set of trusted CAs, watch the configmap containing the pods's CAs, and if the contents change, exit the container, so that we get restarted with the new CA content.

watch for changes in trusted CA configmap

---

config/manager/deployment.yaml
manifests/01_deployment.yaml

Dependent on the speed at which other components are restarted during a 4.1 to 4.2 upgrade, the CCO could be upgraded to a version that expects a trust bundle before it's fulfilled all credential requests thus causing the upgrade to deadlock because the CNO has not yet populated the trust bundle. Therefore, only utilize the trust bundle when it exists.

Bug 1758666: copy trust bundle when actually defined

---

manifests/01_operator_configmap.yaml
pkg/apis/cloudcredential/v1/credentialsrequest_types.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/credentialsrequest/status.go
pkg/controller/credentialsrequest/status_test.go
pkg/controller/secretannotator/aws/reconciler.go
pkg/controller/secretannotator/aws/reconciler_test.go
pkg/controller/secretannotator/azure/reconciler.go
pkg/controller/secretannotator/gcp/reconciler.go
pkg/controller/secretannotator/gcp/reconciler_test.go
pkg/controller/utils/utils.go

Introduces the optional cloud-credential-operator-config ConfigMap. If
present, with a "disabled" key set to "true", all controllers will no-op
and the ClusterOperator will report available=true, progressing=false,
degraded=false, upgradable=true.
Unfortunately this requires two of our three controllers to have explicit code to
check right now. The configmap monitoring controller remains running.

Add support for manually disabling the operator.

---

manifests/01_operator_configmap.yaml

In current form the CVO will undo anything a user tries to do as it
believes it owns this configmap. Adding this annotation will have the
CVO only create it and then leave it be.

Annotate new configmap so CVO will allow changes.

---

cmd/manager/main.go
pkg/controller/add_metrics.go
pkg/controller/configmap/configmap_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/metrics/metrics.go
pkg/controller/metrics/metrics_test.go
pkg/controller/secretannotator/aws/reconciler.go
pkg/controller/secretannotator/azure/reconciler.go
pkg/controller/secretannotator/gcp/reconciler.go

Add the bare minimum of metrics reporting. Report total number of cred requests, and the reconcile times for the various controllers.
Note: when running the controller locally, you can view the metrics at http://localhost:2112/metrics

initial scaffolding for CCO metrics

---

pkg/controller/metrics/metrics.go
pkg/controller/metrics/metrics_test.go

should start to see these kinds of metrics being reported
```
cco_credentials_requests_conditions{condition="Ignored"} 8
cco_credentials_requests_conditions{condition="MissingTargetNamespace"} 1
```

add metrics reporting the count of credReqs with conditions

---

config/kustomization.yaml
config/manager/deployment.yaml
config/manager/metrics-service.yaml
config/manager/namespace.yaml
config/manager/servicemonitor.yaml
config/rbac/prometheus_role.yaml
config/rbac/prometheus_role_binding.yaml
manifests/01_deployment.yaml
pkg/assets/bindata.go

this involves:
update the kustomize pieces to use these new files when generating manifests.

enable prometheus to scrape metrics

---

config/kustomization.yaml
config/manager/prometheusrule.yaml
manifests/01_deployment.yaml
pkg/assets/bindata.go

define two alerts in the PromtheusAlert object to fire when a CredentialsRequest has any of the following conditions:
MissingTargetNamespace for more than 5 minutes
ProvisioningFailed for more than 5 minutes

add initial prometheus alerts

---

config/manager/prometheusrule.yaml
manifests/01_deployment.yaml
pkg/assets/bindata.go

also, rename the alerts in Prometheus so that all the CCO-specific credentials will be grouped by name

alert on insufficient cluster cloud creds

---

manifests/05_deployment.yaml
manifests/07_cred-iam-ro.yaml
manifests/10_cluster-operator.yaml

Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

Add manifest annotations for hosted deployment exclusions

---

Makefile
config/manager/namespace.yaml
config/rbac/prometheus_role.yaml
manifests/05_deployment.yaml
pkg/assets/bindata.go

this is so that the 'render' subcommand can continue to have access to the namespace when generating objects for running as a static pod
also fix up some annotations that only went into the generated manifests/05_deployment.yaml (instead of the "source" config/rbac/prometheus_role.yaml)

add namespace to config/manager/

---

Makefile
config/manager/namespace.yaml
config/manager/prometheusrule.yaml
config/rbac/prometheus_role.yaml
manifests/05_deployment.yaml
pkg/assets/bindata.go

use the 'up' metric to detect when the CCO pod is down (ie Promtheus cannot scrape metrics).

Bug 1717255: add alert for when operator is down

---

config/manager/prometheusrule.yaml
manifests/05_deployment.yaml
pkg/assets/bindata.go

using the 'message' annotation on an alert will allow it to be viewed from within the OpenShift web console

Bug 1776704: change prometheus from summary to message

---

pkg/azure/actuator_test.go
pkg/azure/minter.go
pkg/azure/passthrough_test.go

Currently when re-reconciling an already-provisioned CredentialsRequest in Azure, the actuator will just always attempt to create a role assignment even if it already exists. There is error handling to catch the "RoleAssignmentExists" error, and it just moves along to the next task.
This results in the Resource Group where the cluster is installed having periodic entries in the Azure console Activity Log for the Resource Group recording these (non-critical) errors:
```
{
"authorization": {
"action": "Microsoft.Authorization/roleAssignments/write",
"scope": "/subscriptions/SUBSCRIPTION_ID/resourceGroups/jdiaz-az-gpqgx-rg/providers/Microsoft.Authorization/roleAssignments/94025186-5e7b-4e18-88de-4625cac3ed19"
},
"level": "Error",
"operationName": {
"value": …
```

Bug 1776079: Azure: check existing role assignments before creating a new one

---

config/manager/servicemonitor.yaml
manifests/05_deployment.yaml
pkg/assets/bindata.go

CCO exposes metrics through HTTP, so no need to fill out HTTPS-specific fields in the ServiceMonitor CR.

Bug 1776394: fix up ServiceMonitor CR

---

config/manager/prometheusrule.yaml
manifests/05_deployment.yaml
pkg/assets/bindata.go

CC is far too generic to be an alert name and confused an
admin (me) when looking at clusters.
Thank you for adding alerts

Use `CloudCredentialOperator` as alert prefix for humans

---

config/manager/prometheusrule.yaml
manifests/05_deployment.yaml
pkg/assets/bindata.go

CC is far too generic to be an alert name.
manual cherry-pick into release-4.3 to resolve the conflicts.
Backports #144

Bug 1781798: Use `CloudCredentialOperator` as alert prefix for humans

---

pkg/controller/credentialsrequest/constants/constants.go
pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/credentialsrequest/status.go
pkg/controller/metrics/metrics.go
pkg/controller/metrics/metrics_test.go

If a condition has previously been firing and later clears, the metrics calucation logic would not have any CredentialsRequests with the condition firing so there would be no updates to the metrics capturing that condition. This means the condition would never clear.
When initializtion a run for calculating current metrics, pre-populate all the failure condition types to '0' so that we ensure metrics are sent/cleared.

Bug 1781109: pre-populate conditions with count of zero

---

pkg/controller/credentialsrequest/credentialsrequest_controller.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go

in the event that a CredentialsRequest object has been recently synced, but has an error condition set, ensure that the CredentialsRequest is re-reconciled to attemp detecting/handling the error condition (so that it can be cleared).
also check the CredentialsRequest.Status.Provisioned flag so that we always re-reconcile if Provisioned != True.

Bug 1779390: force reconcile if any error conditions are set or !Provisioned

---

config/manager/deployment.yaml
config/manager/prometheusrule.yaml
config/rbac/prometheus_role.yaml
manifests/05_deployment.yaml
pkg/assets/bindata.go

The annotation was in the wrong resource. It needs to be applied to both the deployment and the prometheus rule.

Fix exclusion annotation for hosted use case

---

pkg/aws/actuator/actuator.go
pkg/aws/utils.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/secretannotator/aws/reconciler.go
pkg/controller/secretannotator/aws/reconciler_test.go
pkg/controller/utils/utils.go

Allow providing an aws region to be used when performing the simulations.
IAM permissions can be defined in a way where permissions are granted as long as the region is set to some specific region(s). Add region info when simulating permissions testing so that we avoid false failures (ie we claim permission denied when it would actually work with an acceptable region set).

Bug 1750338: improve permissions simulation by adding region info

---

pkg/controller/metrics/metrics.go
pkg/controller/metrics/metrics_test.go

If CCO is disabled it should not be triggering Prometheus alerts. Skip reporting condition metrics if CCO has been disabled.

Bug 1794536: don't report conditions when CCO is disabled

---

pkg/aws/actuator/actuator.go
pkg/aws/client.go
pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
pkg/controller/secretannotator/aws/reconciler.go
pkg/controller/secretannotator/aws/reconciler_test.go

this allows the client setup code to insert the region info, which in turn allows the AWS SDK to use the alternative API endpoints when connecting to the AWS China regions.
also reorder parameters so we are consistently using region before infraName.

provide region when setting up an AWS client

---

Dockerfile
config/manager/namespace.yaml
manifests/00_namespace.yaml
pkg/assets/bindata.go

Remove the label that was running CCO as a privileged pod. It is unnecessary for the kinds of operations that CCO needs to perform in cluster.
Removing the label makes the file copy of any provided certificate bundles fail (used for things like global proxy settings). Fix up the permissions at container build time to allow the Pod startup to continue to be able to copy over any certificate bundle mounted into the pod.
The label appears to have no effect when CCO is running on the bootstrap node, so there is no need to maintain a Namespace definition for use only during bootstrap (like we must do for the bootstrap-only Pod definition).

Bug 1806892: no need to run CCO as privileged pod

---

pkg/ovirt/actuator.go
pkg/ovirt/actuator_test.go

Related to: https://github.com/openshift/installer/pull/3261

Bug 1794313: Some cluster operators fail to come up because RHV CA is not trusted by a pod

---

pkg/aws/client.go

users like openshift installer configure AWS clients with properties like
- configure the max retires for the client to wait longer for throttle errors.
- configure the service endpoint resolver in larger ecosystem of other AWS APIs
- configure and control the user agent sent with AWS requests.
The existing method doesn't allow the freedom mentioned above and is too restrictive to use as lib.

pkg/aws: allow users to create a client from IAM client

---

pkg/controller/utils/utils.go

Older clusters that have been upgraded over time will have a correspondingly old version of the Infrastructure CR where Status.PlatformStatus did not exist.
Detect that case, and return an empty region string. The AWS client code will just use the defaults, and the permissions simulations will simply not include the region as part of the simulation.

Bug 1813343: handle old Infrastructure objects without PlatformStatus

---

cmd/manager/render.go

allow explicitly setting a --manifests-dir where the render process should look for the CCO configmap to determin whether or not to enable CCO during bootstrap.

add explicit --manifests-dir for render bootstrap

---

config/manager/deployment.yaml
manifests/05_deployment.yaml
manifests/image-references
pkg/assets/bindata.go

This gets the payload image for `aws-pod-identity-webhook` into the operator.  After this, we can start adding code to this operator to manage this admission webhook and other AWS pod identity bits.
fyi @derekwaynecarr

add aws-pod-identity-webhook to image refs and deployment

---

cmd/manager/render.go

this lets the installer bootkube.sh script run properly https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L354

create at least the empty dir even if CCO is disabled

---

Makefile
manifests/05_deployment.yaml
pkg/cmd/render/render.go

Two small commits adding a `make verify-deps` target for ensuring the integrity of the `vendor` tree and follow-on to #177 renaming the containers from `manager` to `cloud-credential-operator`.
After this, I'll open a PR against openshift/release to run the new build-machinery make targets (`test`, `verify`, and `verify-deps`) and we can remove the old ones.

add verify-deps target and rename containers

---

docs/disabled-operator.md

Don't hide the apiVersion field. Fixes https://issues.redhat.com/browse/CO-878

fix rendering of example configmap

---

pkg/apis/cloudcredential/v1/aws_types.go
pkg/aws/actuator/actuator.go

Added support for conditions in AWS provider
Allows to use the same form as JSON conditions to specify rules to apply - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html
```yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
.....
- iam:PassRole
condition:
"Null":
key: "true"
effect: Allow
resource: '*'
```

Bug 1815219: CO-876: allow defining Conditions in AWS CredentialsRequest

---

pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go

In the event that the install-time creds secret is removed (kube-system/aws-creds), reconciling the read-only CredentialsRequest would fail.
It is okay to just use the read-only credentials to make sure that no updates are needed to the read-only CredentialsRequest.
Also, update the function for handling whether a CredentialsRequest already exists so that it covers the passthrough credentials case where the AWS user fields are empty.

Bug 1838718: do not special-case handling read-only credentialsRequest

---

pkg/operator/utils/utils.go

New operator in 4.5 will migrate existing Infrastructure object to include PlatformStatus.AWS.Region. Add a note to remind us that we can one day remove this legacy handling support.

add note explaining when legacy handling can be removed

---

Makefile

Currently 'make install' is failing because the name of the CCO CRD file has
changed from '00_v1_crd.yaml' to '00-crd.yaml'. This PR fixes it.

Fix failing make install

---

pkg/apis/cloudcredential/v1/credentialsrequest_types.go
pkg/cmd/render/render.go
pkg/operator/constants/constants.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
pkg/operator/secretannotator/aws/reconciler.go
pkg/operator/secretannotator/aws/reconciler_test.go
pkg/operator/secretannotator/azure/reconciler.go
pkg/operator/secretannotator/gcp/reconciler.go
pkg/operator/secretannotator/gcp/reconciler_test.go
pkg/operator/secretannotator/vsphere/reconciler.go
pkg/operator/secretannotator/vsphere/reconciler_test.go
pkg/operator/utils/utils.go

don't want to make it part of the published info into openshift/api as we have plans to make a more formal config object

internalize location of CCO configmap

---

pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/aws/client.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
pkg/operator/oidcdiscoveryendpoint/controller.go
pkg/operator/secretannotator/aws/reconciler.go
pkg/operator/secretannotator/aws/reconciler_test.go
pkg/operator/utils/aws/utils.go
pkg/operator/utils/aws/utils_test.go
pkg/operator/utils/utils.go

Search through the cluster's Infrastructure object to see if an alternate IAM endpoint is specified, and use it when creating the AWS client.

use alternate IAM endpoints if specified

---

README.md
pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/azure/client.go
pkg/azure/passthrough.go
pkg/azure/passthrough_test.go
pkg/gcp/actuator/actuator.go
pkg/openstack/actuator.go
pkg/operator/awspodidentity/controller.go
pkg/operator/credentialsrequest/actuator/actuator.go
pkg/operator/credentialsrequest/constants/constants.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/operator/credentialsrequest/status.go
pkg/operator/credentialsrequest/status_test.go
pkg/ovirt/actuator.go
pkg/vsphere/actuator/actuator.go

Enhance safety by making sure the recently documented root cred removal process marks upgradable false until the user restores the credentials.
We also now reconcile all cred requests on any change to a secret that looks like one of our supported cluster parent cred secrets.

Upgradable false when parent creds removed.

---

manifests/0000_90_cloud-credential-operator_01_prometheusrole.yaml
manifests/0000_90_cloud-credential-operator_03_servicemonitor.yaml
manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
manifests/01-cluster-role.yaml
manifests/01-service.yaml
manifests/02-kube-rbac-proxy-config.yaml
manifests/03-deployment.yaml
manifests/image-references

Add kube-rbac-proxy container to CCO deployment listening on :8443 and forwarding traffic to :2112 (the CCO container's metrics port).
New ConfigMap with configuration for the kube-rbac-proxy container.
Update cco-metrics service to request certs to be created (for use by kube-rbac-proxy container).
Update ServiceMonitor to tell Prometheus to scrape using https.
Grant Prometheus role permissions for fetching metrics.
Update role permissions so that kube-rbac-proxy container can perform its tasks.
Also, remove unused port definition in CCO container definition (webook-server port number 9876).

Bug 1809194: expose metrics over https

---

pkg/operator/awspodidentity/controller.go

@dgoodwin @abhinavdahiya @wking 
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1846200
This changes the behavior from fatal termination of the whole operator when `AWS_POD_IDENTITY_WEBHOOK_IMAGE` is not set, to just disabling the `podidentitywebhook` controller within the operator.

Bug 1846200: make AWS_POD_IDENTITY_WEBHOOK_IMAGE not set non-fatal

---

manifests/03-deployment.yaml

instead of forcing debug.
This is to address openshift/cloud-credential-operator#207
But it doesn't address how to actually set it to debug mode if desired.

let CCO use the default info log-level

---

pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
pkg/operator/credentialsrequest/status.go
pkg/operator/credentialsrequest/status_test.go
pkg/util/clusteroperator/status.go
pkg/util/clusteroperator/status_test.go

@dgoodwin @joelddiaz @derekwaynecarr 
This PR refactors the code responsible for updating the `cloud-credential` `ClusterOperator` status.
Previous to the recent additions of the `awspodidentity` and `oidcdiscoveryendpoint` controllers, the only controller whose status effected the `ClusterOperator` status was the `credentialsrequest` controller and thus, the code to modify the status conditions was authoritatively controlled there.
However, with the new controllers, there are now 3 controllers whose state should be reflected in the status conditions.
The PR seeks to pull the code responsible for reconciling the `ClusterOperator` status out of the `credentialsrequest` controller so that other controllers can also register as `StatusHandlers` that can impact the status conditions and …

refactor ClusterOperator status updates

---

pkg/apis/cloudcredential/v1/types_credentialsrequest.go

These changes make the generated CRD from openshift/api exactly match the current CRD in cloud-credential-operator/manifests/00-crd.yaml

annotate CredentialsRequest structs for openshift/api

---

pkg/operator/oidcdiscoveryendpoint/controller.go
pkg/util/clusteroperator/status.go
pkg/util/clusteroperator/status_test.go

/cc @joelddiaz 
/assign @dgoodwin 
Following https://github.com/openshift/cloud-credential-operator/pull/213, this PR adds a status handler to the `oidcdiscoveryendpoint` controller so that if it is having problems, the overall OperatorStatus is Degraded with informative message why.
fyi @derekwaynecarr

oidcdiscoveryendpoint: add status handler

---

pkg/azure/minter.go

When creating the authorizer for communicating with Azure, the settings need to use the ActiveDirectory endpoint appropriate for the cloud environment.

minter: azure authorizer needs to have ActiveDirectory endpoint specified

---

pkg/operator/awspodidentity/controller.go
pkg/operator/credentialsrequest/status.go
pkg/operator/secretannotator/status/status.go

cloud-credential's related objects have wrong `resource` casing. Thats causing inability to create links in the console:
/assign dgoodwin csrwng

Bug 1868328: Fix cases in cloud-credential's related objects

---

go.mod
pkg/cmd/operator/cmd.go

We were using the defaults from controller runtime previously:
lease duration: 15s
renew deadline: 10s
retry period: 2s
This meant that the active leader was writing to etcd every 2 seconds to
update the lease, which is excessive writing and spawned the bug above.
We now implement leader election using the underlying client-go code to
get access to ReleaseOnCancel, which is not presently exposed in
controller-runtime.
This allows us to immediately release the lock on normal shutdown
eliminating delay before another pod takes over, as well as startup
delay when doing development etc.

Bug 1858403: Use client-go leader election to write less.

---

manifests/05_deployment.yaml

allow downgrading from 4.6 (where we do specify a serviceaccount)

Bug 1873345: specify a serviceaccount in the deployment

---

Dockerfile

first move to 1.15 (later PR will update openshift/api vendoring to 4.6 branch which requires go1.14 or greater)

Bug 1878163: move to go 1.15

---

bindata/v4.1.0/aws-pod-identity-webhook/mutatingwebhook.yaml
pkg/assets/v410_00_assets/bindata.go

@dgoodwin @joelddiaz 
xref https://bugzilla.redhat.com/show_bug.cgi?id=1880944
derived from https://github.com/aws/amazon-eks-pod-identity-webhook/pull/79
fixes #230

Bug 1880944: aws-pod-identity: add sideEffects to webhook

---

pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/azure/actuator.go
pkg/azure/passthrough.go
pkg/gcp/actuator/actuator.go
pkg/openstack/actuator.go
pkg/operator/constants/constants.go
pkg/operator/credentialsrequest/actuator/actuator.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/operator/credentialsrequest/status.go
pkg/operator/credentialsrequest/status_test.go
pkg/operator/secretannotator/aws/reconciler.go
pkg/ovirt/actuator.go
pkg/vsphere/actuator/actuator.go

There are two new credentials coming in 4.6, but if a manual mode user attempts to upgrade without them, the upgrade will fail.
This change encodes the secret names we know are coming, we ensure they exist and if not you are upgradeable=false. This condition does not affect 4.5.x upgrades, only 4.5 to 4.6.
Additionally to improve user experience, we are doing a hacky reconcile to get the status update that would clear upgradeable false when these secrets are created. This involves reconciling a fake cred request NamespacedName which we watch for and return early. In 4.7 we hope to break status updating out into it's own controller for a number of reasons, at which point this hack can be removed.

Bug 1871713: Mark Manual Clusters  Upgradeable=False If 4.6 Cred Request Secrets Are Not Provisioned

---

manifests/03-deployment.yaml

The revamped leader election in 4.6 is not working correctly if the
Deployment is modified. Under the default Deployment strategy of rolling
update, a new pod is brought up before the old is terminated. The new
pod leader election has already determined someone else is leader before
the old releases it's lock, and will wait the full renew interval of 270
seconds before checking again.
To fix we switch to the recreate strategy which will delete the old pod
first, then create the new. This seems the desired strategy for leader
election based operators.

Bug 1882505: Fix stalled leader election after Deployment updates.

---

pkg/operator/metrics/metrics.go

We now will report 1 for any modes in use, and anything not in use will
be explicitly cleared in case we transitioned modes since the pod was
started.
This is to make the metric easier to consume across the entire fleet.
/assign @joelddiaz 
/cc @akhil-rane

Stop reporting mode metrics for unused modes.

---

pkg/cmd/operator/cmd.go

When hard-stopping a debugging session, the leader election cleanup doesn't get to run. Provide a way to skip all the leader election startup to speed up the development loop.

allow skipping leader election

---

Dockerfile

Updating ose-cloud-credential-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cloud-credential-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-cloud-credential-operator builder & base images to be consistent with ART

---

README.md
manifests/05-gcp-ro-credentialsrequest.yaml
pkg/aws/actuator/actuator.go
pkg/gcp/actuator/actuator.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go

enable GCP read only creds to be used when root creds missing

---

manifests/0000_90_cloud-credential-operator_04_alertrules.yaml

The alert was born with a 5m `for` as CCOperatorDown in 63af2de417 (#132).  But folks are unlikely to be churning their creds so quickly that the occasional longer operator outage is worth waking an admin with a midnight alarm.  This is true in general, although folks have been revisiting this alert in the context of 4.5->4.6 updates, where a [shift in leader leasing][1] has lead to a risk of an 8 minute delay as a 4.6 operator waits patiently before picking up a lease abandoned by a 4.5 operator.  The new 20m threshold allows for two such delays with room to spare, and also ensures we aren't waking folks up if theres a brief network or registry outage while pods are being rescheduled or anything minor like that.  Some things are worth more agressive thresholds, but I don't think the cred …

Bug 1889540: manifests: Allow 'for: 20m' for CloudCredentialOperatorDown

---

pkg/aws/client.go
pkg/operator/utils/aws/utils.go

When a cluster is installed in a AWS C2S region, access to the AWS API requires a custom CA bundle for trust. The custom CA bundle is read from the "ca-bundle.pem" key of the kube-cloud-config ConfigMap in the openshift-config-managed namespace.
https://issues.redhat.com/browse/CORS-1584

aws: support custom CA bundle for AWS API

---

pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go

Start storing a usable AWS credentials config file in the 'credentials' field of the Secret. This should allow a consumer of the credentials to just point to the config stored in that field when setting up an AWS client.
Also make sure we are re-queuing CredentialsRequest objects every 1hr10min (so that we are at least periodically doing a full reconcile to restore any lost credentials).

add new credentials field for AWS Secrets

---

Makefile
bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
manifests/00-crd.yaml
pkg/apis/cloudcredential/v1/types_credentialsrequest.go
pkg/assets/bootstrap/bindata.go

In order to make 'oc explain' work we need to enable field pruning
by setting preserveUnknownFields to false
jira: https://issues.redhat.com/browse/OCPBUGSM-17971

Bug 1880785: Fix CredentialsRequest missing description in 'oc explain'

---

manifests/05_deployment.yaml

Bug 1898199: manifests: Allow 'for: 20m' for CloudCredentialOperatorDown

---

bindata/v4.1.0/aws-pod-identity-webhook/mutatingwebhook.yaml
pkg/assets/v410_00_assets/bindata.go

The pod-identity webhook should ignore the run-level 0 namespaces b/c there is a race where if the webhook is running before the non-bootstrap API server is running, the install will error out.

Bug 1903226: exclude run-level 0 namespaces from MutatingWebhook for Pods

---

pkg/aws/actuator/actuator.go
pkg/gcp/actuator/actuator.go
pkg/openstack/actuator.go
pkg/operator/constants/constants.go
pkg/operator/utils/utils.go
pkg/vsphere/actuator/actuator.go

Refactor AWS upgradeable checking so that other platforms can use the logic.
Add new GCP, OpenStack, and vSphere secrets to check/set upgradeable on.

Bug 1916454: checking 4.7 creds

---

Makefile

Images prow job is failing with the old registry, moving to a new one

Bug 1920695: Update OpenShift CI registry in Makefile

---

README.md

We publish official docs on how to run CCO in Manual mode for Azure and GCP. Update our readme to reflect that.

specify Azure and GCP as supporting Manual mode

---

pkg/apis/cloudcredential/v1/types_credentialsrequest.go
pkg/operator/cleanup/cleanup_controller.go
pkg/operator/cleanup/cleanup_controller_test.go
pkg/operator/cleanup/status.go
pkg/operator/constants/constants.go
pkg/operator/controller.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
pkg/operator/credentialsrequest/status.go
pkg/operator/credentialsrequest/status_test.go
pkg/operator/utils/utils.go

This PR adds a controller to remove the credentials requests no longer required by the CCO

Add controller to cleanup stale credentials requests

---

pkg/aws/actuator/actuator.go
pkg/gcp/actuator/actuator.go
pkg/openstack/actuator.go
pkg/operator/constants/constants.go
pkg/operator/utils/utils.go
pkg/vsphere/actuator/actuator.go

Manual backport of #280 
Refactor AWS upgradeable checking so that other platforms can use the logic.
Add new GCP, OpenStack, and vSphere secrets to check/set upgradeable on.

Bug 1916868: Check 47 creds backport

---

bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
manifests/00-crd.yaml
pkg/apis/cloudcredential/v1/types_credentialsrequest.go
pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
pkg/assets/bootstrap/bindata.go

The new field will not be used by CCO but is needed for ccoctl tool to
set up access control in the cloud provider.

Add a CredentialsRequest field to store service account names

---

manifests/05-iam-ro-credentialsrequest.yaml

For a new way of managing OpenShift credentials on AWS to work, using Security
Token Service, we need external tooling to know the service account names from
the Credentials Request manifest so that it can create IAM Roles that can be
assumed only by those specific service accounts.
Managing credentials using STS ref: https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md
Tooling design ref: https://issues.redhat.com/browse/CCO-60
/cc @joelddiaz

Add service account names to credentials request manifest

---

pkg/aws/actuator/actuator.go
pkg/operator/constants/constants.go
pkg/operator/metrics/metrics.go
pkg/operator/metrics/metrics_test.go

Allow metrics reporting to detect and report a cluster where at least one
CredentialsRequest secret is configured for pod identity/STS.
CredentialsRequest Secret contains pod identity/STS content
pod identity/STS Secret content
xref: https://issues.redhat.com/browse/CCO-61

report STS as a submode of Manual

---

go.mod
pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/gcp/actuator/actuator.go
pkg/openstack/actuator.go
pkg/operator/constants/constants.go
pkg/operator/status/status_controller.go
pkg/operator/utils/utils.go
pkg/operator/utils/utils_test.go
pkg/vsphere/actuator/actuator.go

Today CCO can mark itself Upgradeable=False if it sees that a Secret (containing credentials) that is required for the next minor upgrade is missing.
If an existing credentials in version 4.X simply needs new permissions in 4.Y, CCO in Manual mode cannot probe to determine this. (CCO being in Manual mode is basically CCO making minimal cloud API calls).
Introduce a system so that any/all platforms will set Upgradeable=False until an annotation has been appllied to CCO's CloudCredential config object.
This will set Upgradeable=False when in Manual mode until the user sets the annotation appropriately.
Additionally, this new annotation can be used to bypass situations that would otherwise have the cluster in Upgradeable=False (advanced use only).
Also: remove checks based on known upcoming …

require annotation before upgrade when in manual mode

---

pkg/operator/metrics/metrics.go

When calculating the metrics, the code will go through CredReq objects
for platforms other than what the cluster is actually deployed on. Do
not error if the SecretRef doesn't exist as that is expected.

no error when SecretRef does not exist

---

manifests/0000_90_cloud-credential-operator_04_alertrules.yaml

The cluster-version operator is responsible for complaining if the cloud-cred operator's deployment is sad, so no need for the operator to handle this directly (we end up doubling up if there's an issue).

manifests/0000_90_cloud-credential-operator_04_alertrules: Drop CloudCredentialOperatorDown

---

pkg/cmd/operator/cmd.go
pkg/operator/configmap/configmap_controller.go

Post proxy CA change, pod was not relinquishing its leader election
quickly due to os.exit. Changed it to run cancel context to propagate
the exit cleanly

Bug 1927017: Context cancel on stopped leading

---

pkg/aws/client.go
pkg/cmd/provisioning/constants.go
pkg/cmd/provisioning/create.go
pkg/cmd/provisioning/identity_provider.go
pkg/cmd/provisioning/identity_provider_test.go
pkg/cmd/provisioning/keypair.go

- [x ] rename param from 'infra-name' to 'name-prefix'
- [x ] name S3 bucket holding OIDC config "<bucket>-oidc" instead of "<bucket>-installer"
- [x ] Generate the issuerURL fingerprint instead of hardcoding

add generate-only mode for ccoctl create identity-provider

---

Makefile
pkg/aws/client.go
pkg/aws/mock/client_generated.go
pkg/cmd/provisioning/constants.go
pkg/cmd/provisioning/create.go
pkg/cmd/provisioning/identity_provider.go
pkg/cmd/provisioning/identity_provider_test.go
pkg/cmd/provisioning/keypair.go
pkg/cmd/provisioning/roles.go
pkg/cmd/provisioning/roles_test.go

This will take a directory with files representing the
CredentialsRequests that need IAM Roles/Policies created and the AWS IAM
Identity Provider ARN and create/update the Roles.
It also supports a '--generate-files-only' param which will place JSON
files of the IAM Roles and the IAM Role Policies that would have been
created (these can be used with the aws cli with the --cli-input-json
parameter).
Also, add make target for running 'go generate' (to update mock clients)
xref: https://issues.redhat.com/browse/CCO-70

iam-roles subcommand

---

cmd/ccoctl/main.go
docs/ccoctl.md
pkg/aws/client.go
pkg/aws/mock/client_generated.go
pkg/cmd/provisioning/delete.go
pkg/cmd/provisioning/identity_provider.go

`ccoctl create` creates resources with the following tag
`openshift.io/cloud-credential-operator/<name-prefix>: owned`
This command takes name-prefix and region as input and deletes all
the resources with the above tag

CCO-73: Add command to delete resources created by ccoctl 

---

docs/ccoctl.md
pkg/cmd/provisioning/all.go
pkg/cmd/provisioning/constants.go
pkg/cmd/provisioning/create.go
pkg/cmd/provisioning/identity_provider.go
pkg/cmd/provisioning/identity_provider_test.go
pkg/cmd/provisioning/keypair.go
pkg/cmd/provisioning/keypair_test.go
pkg/cmd/provisioning/roles.go

generate manifests for installer for identity-provider and iam-roles subcommands
place secrets in the --output-dir/manifests directory for each CredentialsRequest being processed.
place the Authentication file in --output-dir/manifests during the identity-provider subcommand.
add 'all' subcommand
this will create the key-pair, identity-provider, and iam-roles (and all the manifests) all in one pass by sequentially running through the 'key-pair', 'identity-provider', and 'iam-roles' subcommands.
xref: https://issues.redhat.com/browse/CCO-72

installer manifests and 'all' subcommand

---

manifests/00-namespace.yaml
manifests/03-deployment.yaml

In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Add management workload annotations

---

README.md
pkg/ovirt/actuator.go
pkg/ovirt/actuator_test.go

This PR removes the ovirt_cafile field from the secret

Bug 1946097: oVirt credentials secret contains unnecessary "ovirt_cafile"

---

manifests/03-deployment.yaml

As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Rename workload annotations

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
pkg/assets/v410_00_assets/bindata.go

Since the pod-identity-webhook exists for user workloads, mark the
priority class as "system-cluster-critical" (not be preempted by user
workloads).

Bug 1954865: add priorityClass to pod-identity Deployment

---

pkg/operator/awspodidentity/controller.go

check the error after applying a CR before reading fields from a
potentialy nil variable

Bug 1954615: do not assume result is valid after error

---

pkg/cmd/provisioning/aws/create_identity_provider.go
pkg/cmd/provisioning/aws/delete.go

After a GetRole() has failed, do not assume the returned value is
non-nil.

Bug 1949862: avoid referencing object after error

---

bindata/v4.1.0/aws-pod-identity-webhook/clusterrole.yaml
bindata/v4.1.0/aws-pod-identity-webhook/mutatingwebhook.yaml
pkg/assets/v410_00_assets/bindata.go
pkg/operator/awspodidentity/controller.go

New kubernetes versions have removed support for v1beta1
MutatingWebhookConfiguration CRs. Migrate to deploying v1.
Update pod-identity-webhook ClusterRole to grant permissions around
certificatesigningrequests (fixes `E0503 15:37:23.227864       1 certificate_manager.go:434] Failed while requesting a signed certificate from the master: cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "system:serviceaccount:openshift-cloud-credential-operator:pod-identity-webhook" cannot create resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope`).
Add the newly required `admissionReviewVersions` field to the v1
MutatingWebhookConfiguration.
Update awspodidentity controller to stop reading in v1beta1 …

Bug 1954765: v1beta1 to v1 mutatingwebhookconfiguration

---

pkg/gcp/actuator/actuator.go
pkg/gcp/client.go
pkg/gcp/mock/client_generated.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
pkg/operator/secretannotator/gcp/reconciler_test.go
pkg/operator/utils/gcp/utils.go
pkg/operator/utils/gcp/utils_test.go

In GCP Passthrough mode, the permissions are dynamically checked before
copying the secret contents over. This is done by performing a
TestIamPermissions() call against the current GCP project.
There are certain permissions that make no sense to check against the
project level. Periodically fetch a list of testable permissions using the
QueryTestablePermissions() API call.
Before making a TestIamPermissions() call, filter the permissions through the
allowed list to avoid needlessly receiving errors when calling TestIamPermissions()
against a GCP Project resource.

Bug 1953077: rework GCP passthrough permissions checking

---

pkg/operator/credentialsrequest/credentialsrequest_controller.go

We were treating our not having a Spec implementation the clusters
Infrastructure platform as an error, but this is normal in BareMetal
clusters which have no CredentialsRequests.
Stop treating as an error and just return that the CredRequest is for
another cloud, which is true, and continue.
/assign @akhil-rane 
/cc @joelddiaz

Bug 1864116: Fix "unsupported platform type" log spamming on BareMetal.

---

pkg/operator/status/status_controller.go

This function is called often when watching all Secrets in the cluster
to determine if we should re-reconcile if the cluster platform is none.
As such it should not be logging anything.

Bug 1962602: Remove log statement in frequently called function.

---

bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
manifests/00-crd.yaml
pkg/apis/apis.go
pkg/assets/bootstrap/bindata.go

migrate to v1 CRDs in anticipation of kube 1.22 dropping support for
v1beta1.
Process used was to first generate v1 CRD into a temporary location:
`_output/tools/bin/controller-gen paths=./pkg/apis/...  crd:crdVersions=v1 output:crd:artifacts:config=tmpcrds`
Next copy the CRD to manifests/00-crd.yaml, and compare for any
unexpected changes.
Add back the `include.release.openshift.io` annotations.
Finally, copy that CRD to
`bindata/boostrap/cloudcredential_v1_credentialsrequest_crd.yaml`.
`make update` will now take any new API changes and update the generated
CRDs appropriately (keeping the v1 CRD).
Also remove broken `go generate` which wasn't actually creating the
deepcopy functions anymore.
xref: https://issues.redhat.com/browse/CCO-65

Bug 1957446: v1beta to v1 for the CredentialsRequest CRD

---

pkg/cmd/provisioning/aws/aws.go
pkg/cmd/provisioning/aws/create-iam-roles.go
pkg/cmd/provisioning/aws/create_identity_provider.go

This should more closely mimic the credentials fetching behavior of the
AWS CLI (which already does read from ~/.aws/config in addition to
~/.aws/credentials).

Bug 1970062: enable shared config files for AWS SDK

---

pkg/cmd/provisioning/aws/delete.go

this fixes delete client not reading from ~/.aws/config

Bug 1970062: delete client should also use shared session function

---

pkg/cmd/provisioning/aws/delete.go

iam.ListRoles results are paginated to 100 items by default. If
an account had more then 100 roles, delete command did not work in
some cases. This commit fixes it by checking if iam.ListRoles
result is truncated, fetching next batch of results and deleting
the roles.
x-ref: https://issues.redhat.com/browse/OCPBUGSM-29969

Bug 1967531: Fix ccoctl delete not removing iam roles

---

pkg/cmd/provisioning/aws/create_all.go

This fixes create-all not reading in creds from ~/.aws/config.

Bug 1970062: use shared session setup in ccoctl create-all

---

README.md
docs/adding-new-cloud-provider.md

x-ref: https://issues.redhat.com/browse/CCO-82

Documentation to add a new cloud provider

---

.codecov.yml
.gitignore
Makefile
hack/codecov.sh

This commit adds
- a `coverage` make rule that runs
- a new codecov.sh script adapted from [the one OSD operators use](https://github.com/openshift/boilerplate/blob/f3c8c8d393f69f83ce9dbdbc0aa72d2e5b9e5d96/boilerplate/openshift/golang-osd-operator/codecov.sh);
and
- a codecov configuration file, stolen directly from [the one OSD operators use](https://github.com/openshift/boilerplate/blob/f3c8c8d393f69f83ce9dbdbc0aa72d2e5b9e5d96/boilerplate/openshift/golang-osd-operator/.codecov.yml).
This is designed to be run in three modes: local, presubmit, and postsubmit.
- In all modes, it runs the go cover tool, scrubs out the stats for generated files, and writes the raw report to `coverage.out`.
- In local mode, that's it.
- Presubmit and postsubmit modes are intended for use in CI jobs, where …

Add code coverage script & make target

---

pkg/cmd/provisioning/ibmcloud/create_shared_secrets.go
pkg/cmd/provisioning/ibmcloud/create_shared_secrets_test.go
pkg/cmd/provisioning/ibmcloud/ibmcloud.go

Related to this PR: https://github.com/openshift/cloud-credential-operator/pull/356
Addresses @joelddiaz 's comment: https://github.com/openshift/cloud-credential-operator/pull/356#discussion_r655475848

Rename ibmcloud command to create-shared-secrets

---

go.mod
vendor/modules.txt

...for consistency with appsre and CI, which are already building against 1.16

Bump go.mod to 1.16

---

pkg/cmd/provisioning/aws/create-iam-roles.go
pkg/cmd/provisioning/aws/create-iam-roles_test.go

For upgrades we need create-iam-roles to update policy for existing
roles with permissions in the new release. We extract credentials
requests manifests from the new release and feed it to
create-iam-roles command.
x-ref: https://issues.redhat.com/browse/CCO-84

ccoctl create-iam-roles should update policies for existing roles

---

pkg/cmd/provisioning/ibmcloud/create_shared_secrets.go
pkg/cmd/provisioning/ibmcloud/create_shared_secrets_test.go

Have seen users to use following set of environments to pass the APIKEY, so this PR is to support all those possible environment varaibles.
```
"IC_API_KEY", "IBMCLOUD_API_KEY", "BM_API_KEY", "BLUEMIX_API_KEY"
```

Bug 1990975: Enhance mechanism of reading ibm cloud apikey

---

.ci-operator.yaml

Currently we are using golang-1.15 image in CI, but go.mod is set to go1.16. This is causing verify-deps test to fail.

Update CI build root image to golang-1.16

---

pkg/cmd/provisioning/ibmcloud/service_id.go

This change allows `ccoctl` to set access policy attributes properly for a specific resource group access. In cases where we want to assign access to just the resource group, the policy attributes should look like the following:
```
{
"attributes":[
{
"name":"accountId",
"value":"my-account-id",
},
{
"name":"resourceType",
"value":"resource-group",
},
{
"name":"resource",
"value":"my-resource-group-id"
}
],
}
```
To compare, the attributes generated without this fix will result in..
```
{
"attributes":[
{
"name":"accountId",
"value":"my-account-id",
},
{
"name":"resourceType",
"value":"resource-group",
},
{
"name":"resourceGroupId",
"value":"my-resource-group-id"
}
],
}
```
.. which does not grant access to the resource group as expected.
This fix will determine if `resourceType == …

Bug 2006364: fix(ibmcloud): Set policy attribute name properly for RG access

---

pkg/azure/actuator.go
pkg/kubevirt/actuator.go
pkg/ovirt/actuator.go

We started to require the upgradeable-to annotation when in manual mode.
Make sure Azure and oVirt behave like the other platforms.

Bug 1976674: make azure and ovirt consistent when in manual mode

---

manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
pkg/operator/credentialsrequest/status.go
pkg/operator/credentialsrequest/status_test.go
pkg/operator/metrics/metrics.go
pkg/operator/metrics/metrics_test.go

Currently, we put CCO in the degraded state when stale credentials are found. When in manual mode, stale credentials are not removed by the cleanup controller and thus upgrade is blocked. This commit stops it and instead we raise an alert warning that cluster admin can see and take necessary action.

Bug 2002152: Stop putting CCO in degraded state when stale credentials are found

---

manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
pkg/aws/mock/client_generated.go
pkg/azure/mock/client_generated.go
pkg/gcp/mock/client_generated.go
pkg/ibmcloud/mock/client_generated.go
pkg/operator/secretannotator/azure/mock/adal_generated.go

As requested in the alerting consistency enhancement
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md, update the prometheus alerts in the repo to add summary and description annotations to each alert.

Bug 2010341: update alerts with summary and descriptions

---

manifests/01-service-delete.yaml

Back in 4.1 we installed a Service named 'controller-manager-service'.
That was subsequently dropped, but any cluster that has upgraded from
4.1 to present keeps the needless Service arround. Re-create the Service
with the delete annotation so that the CVO can properly clean this up.

Bug 1977319: cleanup orphaned Service 'controller-manager-service'

---

pkg/cmd/provisioning/ibmcloud/create_service_id.go
pkg/cmd/provisioning/ibmcloud/refresh-keys.go
pkg/cmd/provisioning/ibmcloud/utils.go

This allows listing of resouce groups with user API keys and Service ID
API keys as well.
This should resolve openshift/cloud-credential-operator#401

Bug 2015133: populate accountID when listing resource groups

---

pkg/cmd/provisioning/gcp/create_all.go
pkg/cmd/provisioning/gcp/gcp.go

This command creates all the required infrastructure in the cloud 
to enable openshift install using gcp workload identity for short lived 
credentials.
x-ref: https://issues.redhat.com/browse/CCO-149

Add ccoctl gcp command to create all the required credentials infra

---

docs/ccoctl.md

Documentation on how you can use ccoctl to setup gcp cloud infra
for workload identity to work with OpenShift cluster.
x-ref: https://issues.redhat.com/browse/CCO-117

Add usage docs for ccoctl gcp

---

pkg/operator/status/status_controller.go
pkg/operator/status/status_controller_test.go

From [the property docs][1]:
> lastTransitionTime is the time of the last update to the current status property.
Restricting the timestamp bumps to the status transitions allows consumers to answer "how long have I been `Degraded=True`?" and similar, which is often more useful than being able to answer "how long have I been `Degraded=True` with exactly this `reason` and exactly this `message`?".  Messages are [only for human consumption][2] anyway, so there should be very few users that care about "... and exactly this `message`".  For folks who do care about reasons, [the `cluster_operator_conditions` metric][3] provides access with Prometheus-scrape precision.
[1]: https://github.com/openshift/api/blob/be1be0e89115702f8b508d351c4f5c9a16e5ae95/config/v1/types_cluster_operator.go#L126 …

Bug 2023832: pkg/operator/status: Only bump lastTransitionTime on status changes

---

.ci-operator.yaml
go.sum

[release-4.9] Bug 2024751: pod-identity-webhook starts without tls

---

docs/ccoctl.md

PR for IBMCloud documentation
xref: https://issues.redhat.com/browse/MULTIARCH-1938

Add doc for ibmcloud

---

pkg/aws/actuator/actuator.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go

AWS passthrough test cases were not asserting that the
CredentialsRequest .spec.secretRef contents matched the root
secret creds.
Fixing this revealed several places in the passthrough path where we
could be doing a better job of bubbling up appropriate errors when the
root credentials are simply not good enough to be passed through to
satisfy the CredentialsRequest.
Lastly, check for and return a potential error that was being ignored.
Add test cases to cover root credentials rotation, and test cases for
when insufficient root creds are found.

Bug 2035315: fix passthrough test cases

---

pkg/cmd/provisioning/gcp/create_service_accounts.go

When setting up workload-identity on GCP, require that there is at least
one entry in .spec.serviceAccountNames so that we can properly restrict
which k8s ServiceAccounts can use the created GCP ServiceAccount.

Bug 2036827: ensure GCP CredsReq has a list of ServiceAccounts

---

manifests/01-operator-config.yaml

The cloud cred operator does not run for ibm-cloud-managed or hypershift. This removes the annotation that includes the config CR in that profile.

Bug 2039085: Exclude operator config from ibm-cloud-managed profile

---

README.md
docs/azure-mint-mod-removal.md

Update docs to reflect removed support for Azure Mint mode
xref: https://issues.redhat.com/browse/CCO-173

Azure passthrough docs

---

pkg/cmd/provisioning/gcp/create_service_accounts.go
pkg/cmd/provisioning/gcp/create_service_accounts_test.go
pkg/cmd/provisioning/gcp/create_workload_identity_pool.go
pkg/cmd/provisioning/gcp/create_workload_identity_pool_test.go
pkg/cmd/provisioning/gcp/create_workload_identity_provider.go
pkg/cmd/provisioning/gcp/create_workload_identity_provider_test.go
pkg/gcp/client.go
pkg/gcp/mock/client_generated.go

Currently, ccoctl for GCP errors out if there are existing resources 
for a given infra name. This PR handles this gracefully by making
behavior consistent with AWS. Added unit tests to ensure the right
behavior.
Also, ccoctl now fetches GCP service accounts based on name
and not on account ID. The account IDs have a random string as
suffix which makes it difficult to use them to fetch existing service
accounts.
x-ref: https://issues.redhat.com/browse/OCPBUGSM-39019

Bug 2037331: Make ccoctl gracefully handle existing gcp workload identity resources

---

pkg/operator/status/status_controller.go
pkg/operator/status/status_controller_test.go

The cloud-cred operator hasn't set explicit happy-state reasons since #213:
> Because, with the new interface, controllers only report non-default conditions, the reasons for being in the expected steady state for the condition is no longer reported (i.e. `ReconcilingComplete` and `NoCredentialsFailing`).
Having an explicit happy reason makes it easier to do things like:
sort_desc(count by (reason) (cluster_operator_conditions{name="cloud-credential",condition="Degraded"}))
without having to worry about empty reason being implicitly happy, or some weird, sad condition that just happened to not get a reason string.
These choices are fairly common.  For example, in [a recent 4.10 CI job][2]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/peri …
```

pkg/operator/status: Set an explicit happy reason/message

---

pkg/cmd/provisioning/alibabacloud/alibaba.go
pkg/cmd/provisioning/alibabacloud/create-ram-users.go
pkg/cmd/provisioning/alibabacloud/create-ram-users_test.go
pkg/cmd/provisioning/aws/aws.go
pkg/cmd/provisioning/aws/create-iam-roles.go
pkg/cmd/provisioning/aws/create-iam-roles_test.go
pkg/cmd/provisioning/aws/create_all.go
pkg/cmd/provisioning/constants.go
pkg/cmd/provisioning/gcp/create_all.go
pkg/cmd/provisioning/gcp/create_service_accounts.go
pkg/cmd/provisioning/gcp/create_service_accounts_test.go
pkg/cmd/provisioning/gcp/gcp.go
pkg/cmd/provisioning/ibmcloud/create_service_id.go
pkg/cmd/provisioning/ibmcloud/create_service_id_test.go
pkg/cmd/provisioning/ibmcloud/delete_service_id.go
pkg/cmd/provisioning/ibmcloud/ibmcloud.go
pkg/cmd/provisioning/ibmcloud/refresh-keys.go
pkg/cmd/provisioning/ibmcloud/refresh-keys_test.go
pkg/cmd/provisioning/utils.go
pkg/cmd/provisioning/utils_test.go

First commit disables processing of resources with feature-gate annotation.
Second commit adds new --enable-tech-preview parameter which allows tech-preview-annotated resources through. Adds several test cases to cover it.

Bug 2035903: handle resources with feature-gate annotation

---

manifests/01-role.yaml
pkg/cmd/operator/cmd.go

We were using ConfigMap-based leader election. We need to migrate to
using Lease instead.
Part 1: Use ConfigMap *and* Lease so we can upgrade smoothly from a
build using just ConfigMap.
Part 2: Remove ConfigMap.
This is part 1.
x-ref: https://issues.redhat.com/browse/CCO-191
epic: https://issues.redhat.com/browse/CCO-182

Leader election migration 1: ConfigMap & Lease

---

pkg/cmd/provisioning/alibabacloud/create-ram-users_test.go
pkg/cmd/provisioning/aws/create-iam-roles_test.go
pkg/cmd/provisioning/gcp/create_service_accounts_test.go
pkg/cmd/provisioning/ibmcloud/create_service_id_test.go
pkg/cmd/provisioning/utils.go
pkg/cmd/provisioning/utils_test.go

Ensure directories and non-yaml files are skipped when reading
CredentialsRequests.

Skip directories when reading credentials requests

---

docs/ccoctl.md
pkg/cmd/provisioning/nutanix/create_shared_secrets.go
pkg/cmd/provisioning/nutanix/create_shared_secrets_test.go

- Return an error to the user if the crederntials requests directory is empty
- Add unit tests for Nutanix create-shared-secrets subcommand
x-ref: https://issues.redhat.com/browse/CCO-108

Add a check for no CredentialsRequest manifest in directory 

---

manifests/03-deployment.yaml

Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-cloud-credential-operator/deployments/cloud-credential-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (containers \"kube-rbac-proxy\", \"cloud-credential-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers \"kube-rbac-proxy\", \"cloud-credential-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or containers …
```

manifests/deployment: comply to restricted pod security level

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
pkg/assets/v410_00_assets/bindata.go

Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be restricted.

Bug 2093986: Make pod identity webhook comply to restricted pod security level

---

docs/ccoctl.md
docs/sts-oidc-bucket-policy.json.tpl
docs/sts-oidc-cloudfront.json.tpl
docs/sts-private-bucket.md
docs/sts.md

Add steps to expose the OIDC endpoint in CloudFront with a private S3 Bucket.
Ref:
- https://issues.redhat.com/browse/SPLAT-617
- https://issues.redhat.com/browse/CCO-221

doc(aws-sts): add alternative to host OIDC configuration in a private bucket using CloudFront

---

manifests/00-namespace.yaml

We dropped the run-level label from this namespace back in 8120317f56 (#159, [4.5][1]).  But because of [how the cluster-version operator reconciles manifest labels][2], dropping a label from the manifest does not remove it from the in-cluster resource when old clusters are updated into the new manifest.  This commit uses [the approach the cluster-version operator used][3] to drop its run-level, by setting the value to an empty string, which the run-level-consuming code treats identically to an unset label.
This avoids errors about:
...container has runAsNonRoot and image will run as root...
when [updating to 4.11][4].  Because the namespace manifest sorts before the deployment manifest, there is probably no need to get this change back into 4.10 manifests, although that wouldn't hurt. …

Bug 2101880: manifests/00-namespace: Set empty openshift.io/run-level

---

pkg/cmd/provisioning/gcp/create_all.go
pkg/cmd/provisioning/gcp/create_service_accounts.go
pkg/cmd/provisioning/gcp/create_workload_identity_pool.go
pkg/cmd/provisioning/gcp/create_workload_identity_provider.go
pkg/cmd/provisioning/gcp/delete.go
pkg/gcp/actuator/actuator.go
pkg/gcp/client.go
pkg/operator/secretannotator/gcp/reconciler.go

ccoctl cli does not know how to leverage the VM's attached service account to talk to GCP APIs. This PR adds that support.

Bug 2100964: Make ccoctl work with credentials fetched from gcloud cli defaults

---

pkg/cmd/provisioning/ibmcloud/service_id.go

This PR contains the changes to fix the panic while generating a secret from a credential request when the Provider spec is empty or wrongly indented, Instead of panic the below error is thrown
```
2022/08/10 14:11:35 Failed to validate the serviceID: Spec.ProviderSpec is empty in powervs-block-csi-driver-operator credentials request
```

Bug 2117474: Fix panic when the Provider spec is empty in credential request

---

docs/ccoctl.md
docs/gcp_workload_identity.md
pkg/apis/cloudcredential/v1/types_gcp.go
pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
pkg/cmd/provisioning/gcp/create_service_accounts.go
pkg/cmd/provisioning/gcp/create_service_accounts_test.go
pkg/cmd/provisioning/gcp/delete.go
pkg/gcp/actuator/actuator.go
pkg/gcp/actuator/policy.go
pkg/gcp/actuator/role.go
pkg/gcp/actuator/utils.go
pkg/gcp/client.go
pkg/gcp/mock/client_generated.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go

Add a new `permissions` API field to GCP provider spec.
Permissions is the list of GCP permissions required to create a
more fine-grained custom role to satisfy the CredentialsRequest.
When both Permissions and PredefinedRoles are specified, the
service account will have union of permissions from both the fields
For permissions specified, a custom role is created and added
to the service account along with the predefined roles.
x-ref: https://issues.redhat.com/browse/CCO-188

Add support for granular GCP permissions using custom roles

---

docs/sts.md
pkg/cmd/provisioning/aws/create-iam-roles.go

By default, AWS Security Token Service (AWS STS) is available 
as a global service, and all AWS STS requests go to a single 
endpoint at https://sts.amazonaws.com. Global requests map 
to the us-east-1 region. AWS recommends using Regional AWS
STS endpoints instead of the global endpoint.
x-ref: https://issues.redhat.com/browse/CCO-257

Make ccoctl use regional STS endpoint by default

---

docs/ccoctl.md
docs/gcp_workload_identity.md
pkg/cmd/provisioning/gcp/delete.go

The CredentialsRequests names are needed in order to clean up the correct service accounts in GCP.
This backports https://github.com/openshift/cloud-credential-operator/pull/489 but only code related to the bug that was fixed by requiring `--credentials-requests-dir` for `ccoctl gcp delete` described in [this comment](https://github.com/openshift/cloud-credential-operator/pull/489#issuecomment-1248733205).
~Creating as draft since tests will rely on https://github.com/openshift/release/pull/33402 to delete the service accounts in GCP.~
[OCPBUGS-2801](https://issues.redhat.com/browse/OCPBUGS-2801)

[release-4.11] OCPBUGS-2801: Backport --credentials-requests-dir for ccoctl gcp delete.

---

docs/ccoctl.md
docs/gcp_workload_identity.md
pkg/cmd/provisioning/gcp/delete.go

The CredentialsRequests names are needed in order to clean up the correct service accounts in GCP.
This backports https://github.com/openshift/cloud-credential-operator/pull/489 but only code related to the bug that was fixed by requiring --credentials-requests-dir for ccoctl gcp delete described in https://github.com/openshift/cloud-credential-operator/pull/489#issuecomment-1248733205.
~Creating as draft since tests will rely on https://github.com/openshift/release/pull/33402 to delete the service accounts in GCP.~
[OCPBUGS-2802](https://issues.redhat.com/browse/OCPBUGS-2802)

[release-4.10] OCPBUGS-2802: Backport --credentials-requests-dir for ccoctl gcp delete.

---

Makefile
bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
bindata/v4.1.0/aws-pod-identity-webhook/poddisruptionbudget.yaml
manifests/01-role.yaml
pkg/assets/v410_00_assets/bindata.go
pkg/operator/awspodidentity/controller.go

[CCO-259](https://issues.redhat.com//browse/CCO-259)
This PR increases the replicas of the aws-pod-identity-webhook deployment from 1 to 2 and adds management of a `PodDisruptionBudget` with `minAvailable=1` for the mutating webhook deployment.

Make pod-identity-webhook deployment HA by default

---

pkg/operator/awspodidentity/awspodidentitywebhook_controller.go
pkg/operator/awspodidentity/awspodidentitywebhook_controller_test.go
pkg/operator/utils/utils.go

Previously, https://github.com/openshift/cloud-credential-operator/pull/492 increased the replicas of the AWS pod identity webhook from 1 to 2. We cannot default deployment replicas=2 on a cluster with a `"SingleReplica"` infrastructure topology so this commit checks the infrastructure object to determine the topology and adjusts the replicas when the topology is `"SingleReplica"`. An error will be returned when the cluster infrastructure object is not found. Default replicas (2) used when no infrastructure topology set and adjust replicas=1 when `"SingleReplica"` topology found.
Additionally, the pod disruption budget will not be deployed on `"SingleReplica"` topology clusters.
Rename the podidentitywebhook controller file to "awspodidentitywebhook_controller.go" and add controller tests …

OCPBUGS-6977: Set pod identity webhook replicas=1 when infrastructure topology is SingleReplica

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
vendor/github.com/openshift/build-machinery-go/make/targets/golang/vulncheck.mk
vendor/github.com/openshift/build-machinery-go/scripts/vulncheck.sh
vendor/modules.txt

Bring in the latest BMG so we can now `make vulncheck` to get a preview of what dependabot might complain about.

Upgrade build-machinery-go: `make vulncheck`

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
pkg/assets/v410_00_assets/bindata.go

Add annotation to webhook deployment for workload pinning, this allows workload admission webhook to correctly modify the resources to allow the workload pinning feature to operate as desired. This annotation already exists on the [operator deployment](https://github.com/openshift/cloud-credential-operator/blob/1f7a2602bf8a9ddec5d8fc29f77215697d9e7c07/manifests/03-deployment.yaml#L20-L22), it's just missing from the webhook.
Related to the enhancements below:
https://github.com/openshift/enhancements/pull/703
https://github.com/openshift/enhancements/pull/1213

OCPBUGS-8666: feat: add workload annotation to pod identity webhook deployment

---

docs/sts-migrate-to-private-bucket.md
docs/sts-oidc-bucket-policy.json.tpl
docs/sts-oidc-cloudfront.json.tpl
docs/sts-private-bucket.md

- Added the document to describe how to migrate the issuer URL from a public S3 Bucket URL to a private solution, using CloudFront distribution.
[SPLAT-950](https://issues.redhat.com/browse/SPLAT-950)
[CCO-281](https://issues.redhat.com/browse/CCO-281)

SPLAT-950: doc/aws-sts : steps to migrate from public bucket to private issuer URL

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
pkg/assets/v410_00_assets/bindata.go

The previous change introducing the annotations had a typo: s/annotation/annotations/.
[OCPBUGS-8666](https://issues.redhat.com/browse/OCPBUGS-8666)

OCPBUGS-8666: Correct pod-identity-webhook annotations for PreferredDuringScheduling.

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
pkg/assets/v410_00_assets/bindata.go

Cherry-picks #520 and #522 to 4.13.
With workload pinning feature introduced in 4.13 we'll need to backport this annotation to 4.13. We've also added tests in origin to help catch these annotations going forward.
/assign @abutcher

[release-4.13] OCPBUGS-10822: Adding missing workload annotations

---

pkg/cmd/provisioning/aws/create_identity_provider.go
pkg/cmd/provisioning/aws/create_identity_provider_test.go

Cherry-pick of https://github.com/openshift/cloud-credential-operator/pull/526
* Allow policies to control publicness of S3 bucket.
* Discontinue setting ACL when uploading OIDC discovery and JWKS documents to the S3 bucket.
* Apply a policy that allows anon read to all files in the bucket.

[release-4.12] OCPBUGS-11707: ccoctl: Enable public anon read access to default OIDC S3 bucket

---

pkg/cmd/provisioning/aws/create_identity_provider.go
pkg/cmd/provisioning/aws/create_identity_provider_test.go

Cherry-pick of https://github.com/openshift/cloud-credential-operator/pull/526
* Allow policies to control publicness of S3 bucket.
* Discontinue setting ACL when uploading OIDC discovery and JWKS documents to the S3 bucket.
* Apply a policy that allows anon read to all files in the bucket.

[release-4.11] OCPBUGS-11708: ccoctl: Enable public anon read access to default OIDC S3 bucket

---

pkg/cmd/provisioning/aws/create_identity_provider.go
pkg/cmd/provisioning/aws/create_identity_provider_test.go

Cherry-pick of https://github.com/openshift/cloud-credential-operator/pull/526
* Allow policies to control publicness of S3 bucket.
* Discontinue setting ACL when uploading OIDC discovery and JWKS documents to the S3 bucket.
* Apply a policy that allows anon read to all files in the bucket.

[release-4.10] OCPBUGS-11717: ccoctl: Enable public anon read access to default OIDC S3 bucket

---

Makefile
pkg/aws/actuator/actutator_e2e_test.go
test/e2e/aws/sts/actutator_e2e_test.go

This should probably merge before the changes to the release config envisioned in the below linked PR, such that the make target will be available to calling by pj-rehearse:
https://github.com/openshift/release/pull/38624

Add a make target and stub for actuator e2e tests

---

pkg/cmd/provisioning/aws/create_identity_provider.go
pkg/cmd/provisioning/aws/create_identity_provider_test.go

[OCPBUGS-13549](https://issues.redhat.com/browse/OCPBUGS-13549)

OCPBUGS-13549: Determine AWS partition based on region for readOnlyAnonUserPolicyTemplate bucket ARN.

---

pkg/operator/credentialsrequest/credentialsrequest_controller.go

We only watch namespaces to react to their creation, and the only information we need about a namespace is its' name, so we can use a partial metadata watch to winnow down the size of our cache. Namespaces don't really store much in spec and status, so this effect is likely to not be enormous, but every bit helps.

PORTENABLE-526: operator: use a partial metadata watch for Namespaces

---

pkg/operator/awspodidentity/awspodidentitywebhook_controller.go

Do not deploy the pod identity webhook when infrastructure ControlPlaneTopology is External since Hypershift deploys the webhook independently.

CCO-394: Do not Add PodIdentityWebhook controller when InfraStatus.ControlPlaneToplogy is External.

---

pkg/apis/cloudcredential/v1/types_azure.go
pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
pkg/azure/clients.go
pkg/azure/mock/client_generated.go
pkg/cmd/provisioning/azure/create_managed_identities.go
pkg/cmd/provisioning/azure/create_managed_identities_test.go
pkg/cmd/provisioning/azure/delete.go

ccoctl azure to create custom roles for each credential request which contains permissions.
When ccoctl azure operates on a credential request which has the new permissions definition, a new custom role will be created for the operator with the specified permissions. This custom role will be added to the list of roles specified, if any, and a role assignment will be created for the associated managed identity.
https://issues.redhat.com/browse/CCO-353

CCO-353: ccoctl to create azure custom roles

---

pkg/operator/status/status_controller.go

Found this while investigating https://github.com/openshift/cluster-kube-apiserver-operator/pull/1423.
If status is modified, the operator must set status to proper values. This ensures that accidents cannot permanently reset status and gives a clear indication that the operator is "live".  This came up as important when operators were NOT live, during cert rotations and we had no indication of problems.

reconcile status when the clusteroperator changes

---

go.mod
manifests/04-cluster-operator.yaml
pkg/apis/cloudcredential/v1/types_credentialsrequest.go
pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/azure/client.go
pkg/cmd/operator/cmd.go
pkg/gcp/actuator/actuator.go
pkg/kubevirt/actuator.go
pkg/kubevirt/actuator_test.go
pkg/openstack/actuator.go
pkg/operator/awspodidentity/awspodidentitywebhook_controller.go
pkg/operator/cleanup/cleanup_controller.go
pkg/operator/controller.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/operator/credentialsrequest/credentialsrequest_controller_azure_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_label_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
pkg/operator/loglevel/controller.go
pkg/operator/metrics/metrics.go
pkg/operator/platform/platform.go
pkg/operator/secretannotator/secretannotator_controller.go
pkg/operator/status/status_controller.go
pkg/ovirt/actuator.go
pkg/vsphere/actuator/actuator.go

The status quo for this controller is to LIST + WATCH all Secrets on the cluster. This consumes
more resources than necessary on clusters where users put other data in Secrets themselves, as we
hold that data in our cache and never do anything with it. The reconcilers mainly need to react to
changes in Secrets created for CredentialRequests, which they control and can label, allowing us
to filter the LIST + WATCH down and hold the minimal set of data in memory. However, two caveats:
- in passthrough and mint mode, admin credentials are also provided by the user through Secrets,
and we need to watch those, but we can't label them
- on existing clusters, secrets exist from previous work these reconcilers did that will not have
Secrets labelled
We could solve the second issue with an interim …

OCPBUGS-15365: *: use a filtered LIST + WATCH on Secrets for AWS STS

---

pkg/cmd/provisioning/azure/create_managed_identities.go
pkg/cmd/provisioning/azure/delete.go

The ccoctl azure subcommand was previously leaking role assignments. This change ensures all associated roleAssignments are removed prior to deleting the user-assigned managed identities.

OCPBUGS-15906: ccoctl azure delete to also delete role assignments

---

manifests/01-role.yaml

We can't restrict CREATE with resourceNames, since the final name of the object is potentially unknown at admission time.

OCPBUGS-15365: manifests: fix rbac

---

pkg/operator/credentialsrequest/credentialsrequest_controller.go

For `updateActuatorConditions()` usage, see inline comments please, basically this PR just cleans up the function to hopefully show conditions are updated properly.
`cr.Status.LastSyncTimestamp` is updated now.

OCPBUGS-16334: Clarify updateActuatorConditions & update lastSync

---

manifests/01-cluster-role.yaml
manifests/01-config-role-binding.yaml
manifests/01-config-role.yaml
pkg/aws/actuator/actuator.go
pkg/cmd/operator/cmd.go
pkg/operator/controller.go
pkg/operator/secretannotator/aws/reconciler.go
pkg/operator/utils/client.go

We just need to read *one* and only *one* ConfigMap, so add a Role to let us and use a live client to just read the thing.

OCPBUGS-16313: pkg/operator: correctly fetch CA for AWS minter

---

manifests/03-deployment.yaml
pkg/apis/cloudcredential/v1/codec.go
pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/aws/utils.go
pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/azure/request.go
pkg/cmd/operator/cmd.go
pkg/cmd/provisioning/alibabacloud/create-ram-users.go
pkg/cmd/provisioning/aws/create-iam-roles.go
pkg/cmd/provisioning/azure/create_managed_identities.go
pkg/cmd/provisioning/gcp/create_service_accounts.go
pkg/cmd/provisioning/ibmcloud/service_id.go
pkg/cmd/provisioning/nutanix/create_shared_secrets.go
pkg/gcp/actuator/actuator.go
pkg/kubevirt/actuator_test.go
pkg/openstack/actuator.go
pkg/operator/cleanup/cleanup_controller_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_azure_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
pkg/operator/credentialsrequest/status_test.go
pkg/operator/metrics/metrics_test.go
pkg/operator/utils/utils.go
pkg/ovirt/actuator.go
pkg/vsphere/actuator/actuator.go
test/e2e/aws/sts/actutator_e2e_test.go

pkg/operator: correctly fetch CA for AWS minter
We just need to read *one* and only *one* ConfigMap, so add a Role to
let us and use a live client to just read the thing.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
cmd: add pprof endpoint
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
*: use a global codec
The codec *is* global and only ever changes at compile-time, so
generally the pattern is to declare it as a package global and
intiialize it in an init() method. 30% of our runtime allocations were
building up the scheme/codec on-demand.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---

*: use a global codec

---

pkg/cmd/provisioning/azure/create_all.go

This will enable `e2e-azure-manual-oidc` to process the CAPI credentials request which is marked `TechPreviewNoUpgrade`.

OCPCLOUD-2012: ccoctl: Add --enable-tech-preview arg to azure create-all subcommand.

---

pkg/cmd/provisioning/azure/create_all.go
pkg/cmd/provisioning/azure/create_managed_identities.go

ccoctl should provide an error when installation and OIDC resource group names are the same to prevent ccoctl from creating resources in the resource group meant to be used for cluster install. The OpenShift installer requires that the resource group in the install-config.yaml be empty when running the installation.

OCPBUGS-16807: ccoctl azure exit with error when OIDC and installation resource group names are the same

---

docs/azure_workload_identity.md
docs/ccoctl.md
pkg/cmd/provisioning/azure/azure.go
pkg/cmd/provisioning/azure/create_all.go
pkg/cmd/provisioning/azure/create_oidc_issuer.go
pkg/cmd/provisioning/azure/create_oidc_issuer_test.go

This requires providing the Azure tenant ID to put within the webhook config in create-all and create-oidc-issuer subcommands which will create the webhook config. The Azure tenant ID is not made available/discoverable by azure-sdk-for-go and the method for knowing the tenant ID depends on the authentication method used. Because of this, we will now need to require the tenant ID as a parameter and only use it as a value to be set in the webhook config.
e2e-azure-manual-oidc will need to be modified to account for this new required command line parameter.

CCO-402: Create Azure AD pod identity webhook config secret manifest in create-all,create-oidc-issuer

---

pkg/apis/cloudcredential/v1/types_azure.go
pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
pkg/cmd/provisioning/azure/create_managed_identities.go

Add a new dataPermissions parameter to the Azure credentials request and plumb it through to the custom role that is attached to the generated user-assigned managed identity.

CCO-413: Add dataPermissions to Azure credentials request.

---

manifests/image-references

Per https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#product-builds-and-becoming-part-of-an-openshift-release-image the image must be listed in an image references file to be picked up by CI nightlies.
> 2. Operands managed by second level operators. These images are pulled into the release payload by virtue of being [specified in an image-references file by a second level operator](https://github.com/openshift/cloud-credential-operator/blob/c2bec26d3734e444666024858e76d4ca80dd31cf/manifests/image-references#L9-L12).

CCO-401: Add azure-workload-identity-webhook to image references.

---

manifests/image-references

Reverts openshift/cloud-credential-operator#586
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
The last 3 [nightlies](https://amd64.ocp.releases.ci.openshift.org/#4.14.0-0.nightly) have failed with:
error: unable to create a release: operator "cloud-credential-operator" contained an invalid image-references file: no input image tag named "azure-workload-identity-webhook"
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem

Revert "CCO-401: Add azure-workload-identity-webhook to image references."

---

pkg/operator/credentialsrequest/credentialsrequest_controller.go

Should now be properly setting the `lastSyncGeneration` as per the non-STS flow.

OCPBUGS-17049: update lastSyncGeneration in STS flow sync success

---

pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go

I think this cures the bug as long as I tracked from the correct part of the code that was setting `cr.status.provisioned` to true despite a failure to actually provision the Secret.

OCPBUGS-16684: Set cr.status.provisioned=false on syncErr path

---

pkg/aws/actuator/actuator.go

17bd3eecfa237 (#228) moved the `CheckPermissionsUsingQueryClient` down to a `!=Passthrough` block, so drop the comment which suggested passthrough creds were checked to confirm sufficient permissions.

pkg/aws/actuator: Drop comment which suggested passthrough permission verification

---

pkg/cmd/provisioning/azure/azure.go
pkg/cmd/provisioning/azure/create_all.go
pkg/cmd/provisioning/azure/create_managed_identities.go
pkg/cmd/provisioning/azure/create_managed_identities_test.go
pkg/cmd/provisioning/azure/create_oidc_issuer_test.go

This optional paramter can be used to specify a resource group containing existing network resources, which (if provided) will be scoped to several network-related operators in addition to the main installation resource group
xref: [OCPBUGS-18246](https://issues.redhat.com//browse/OCPBUGS-18246)
Virtual network related permissions were discovered in the following credentials requests (recent nightly):
```
0000_30_machine-api-operator_00_credentials-request.yaml
53:    - Microsoft.Network/virtualNetworks/delete
54:    - Microsoft.Network/virtualNetworks/read
55:    - Microsoft.Network/virtualNetworks/subnets/delete
56:    - Microsoft.Network/virtualNetworks/subnets/join/action
57:    - Microsoft.Network/virtualNetworks/subnets/read
58:    - Microsoft.Network/virtualNetworks/subnets/write …
```

OCPBUGS-18246: Add networkResourceGroupName parameter for Azure

---

cmd/cloud-credential-operator/main.go
manifests/01-webhook-cluster-role-binding.yaml
manifests/01-webhook-cluster-role.yaml
manifests/01-webhook-role-binding.yaml
manifests/01-webhook-role.yaml
manifests/02-webhook-sa.yaml
manifests/03-webhook-deployment.yaml
pkg/cmd/webhookoperator/cmd.go
pkg/operator/controller.go
pkg/operator/podidentity/podidentitywebhook_controller.go

Managing these objects is a disjoint operation from the normal CCO mode, and requires different permissions. Splitting them lets us deploy these as needed.

CCO-421: *: split pod identity webhooks from core controller

---

pkg/cmd/provisioning/azure/create_managed_identities.go

The Azure cloud controller manager needs access to modify the load balancers, which may exist in a network resource group. This change adds that access to the network resource group when using azure create-manage-identities.

OCPBUGS-21745: azure create-managed-identites to add cloud controller manager to network resource group

---

pkg/cmd/provisioning/azure/create_oidc_issuer.go
pkg/cmd/provisioning/azure/create_oidc_issuer_test.go

The cloud provider is changing the default behavior of the buckets to not be publicly available. This change explicitly sets the bucket created by 'ccoctl azure create' to allow public blob access.

OCPBUGS-22369: explicitly set azure oidc bucket to allow public blob access

---

pkg/cmd/provisioning/gcp/create_all.go
pkg/cmd/provisioning/gcp/create_service_accounts.go
pkg/cmd/provisioning/gcp/create_service_accounts_test.go
pkg/cmd/provisioning/gcp/create_workload_identity_provider.go
pkg/cmd/provisioning/gcp/delete.go
pkg/gcp/actuator/actuator.go
pkg/gcp/actuator/policy.go
pkg/gcp/actuator/role.go
pkg/gcp/actuator/utils.go
pkg/gcp/actuator/utils_test.go
pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go

Because CCO now manages custom roles per-project instead of per-cluster, the name format is fixed instead of random so that it all clusters within the same project will use the same custom roles.
Additionally, by default, custom roles will not be deleted.  To delete per-project custom roles, pass the `--force-delete-custom-roles` flag to `ccoctl`.
xref: https://issues.redhat.com/browse/CCO-430
/assign @jstuever 
/cc @abutcher

CCO-430: Use per-project custom roles instead of per-cluster custom roles

---

pkg/cmd/operator/cmd.go

This is phase 2 of the cutover from ConfigMaps to Leases for leader election. See [CCO-191](https://issues.redhat.com//browse/CCO-191) / #446 / 0139ffd3 for phase 1.
Closes [CCO-192](https://issues.redhat.com//browse/CCO-192)

CCO-192: Use Leases for leader election

---

pkg/vsphere/actuator/actuator.go

The behavior recently changed to patching the credential secrets as opposed to updating them. As a result, sometimes when a credential is changed it can continue to have pieces of the old credential.
This change overrides the entire vphere credential data to be explicitly set to the new credential. This will remove all old credential data when syncing the new credential.

OCPBUGS-20478: Explicitly set the vsphere secret credential data on sync.

---

Makefile
pkg/apis/cloudcredential/v1/types_azure.go
pkg/azure/actuator.go
pkg/azure/actuator_test.go
pkg/azure/const.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
test/e2e/azure/azident/actutator_e2e_test.go

Adds Azure Workload Identity (Timed Access Token) support and e2e test and unit tests.
`pkg/azure/actuator_test.go` should get a review for changes that were needed to pre-existing unit tests. The changes were needed because of the requirements of the new detection for Workload Identity in-use flow.
Known issues:
* Reviewed the several bug fix PRs against the AWS STS work, most fixes were in credentialsrequest_controller so their all present for this Azure branch as well, just OCPBUGS-16684 had an actuator change that seemed to be needed here.
* PR to add calling make target to azure e2e is here: https://github.com/openshift/release/pull/42126

CCO-372: Azure Workload Identity info in CredsRequests creates a Secret

---

pkg/cmd/provisioning/aws/create_identity_provider.go
pkg/cmd/provisioning/aws/create_identity_provider_test.go

DNS suffix is different in China regions `.amazonaws.com.cn` vs `.amazonaws.com` so discover the DNS suffix based on the partition via AWS SDK using the region.

OCPBUGS-13597: Discover AWS dns suffix from partition and region.

---

pkg/gcp/actuator/actuator.go
pkg/gcp/actuator/policy.go
pkg/gcp/actuator/role.go
pkg/gcp/client.go
pkg/gcp/mock/client_generated.go

Previously, the GCP sync would error when attempting to add permissions to a custom role that was deleted and pending pruning. This change ensures the custom roles are undeleted.

OCPBUGS-23178: Enable GCP sync to undelete custom roles

---

manifests/05-gcp-ro-credentialsrequest.yaml

Switch the gcp-ro credential request to use granular permissions. It is only used by the actuator.needsUpdate() function. Everything else escalates to the root service account. The needsUpdate() function currently requires the following permissions as per the specified function calls.
iam.roles.get:
getPermissionsFromRoles()
serviceAccountNeedsPermissionsUpdate()
iam.serviceAccountKeys.list
serviceAccountKeyExists()
iam.serviceAccounts.get:
GetServiceAccount()
serviceAccountNeedsPermissionsUpdate()
resourcemanager.projects.get:
checkServicesEnabled()
resourcemanager.projects.getIamPolicy:
serviceAccountNeedsPermissionsUpdate()
serviceusage.services.list:
checkServicesEnabled()

CCO-244: gcp-ro-credentialrequest to use granular permissions

---

docs/sts.md

1. Add a comment about the name flag in step 3 of in-place migration.

NO-JIRA: Update docs/sts.md

---

pkg/operator/metrics/metrics.go

The controller-runtime client used in metrics calculator, i.e. 
https://github.com/openshift/cloud-credential-operator/blob/77a68ad01e75162bfa04097b22f80d305c192439/pkg/operator/metrics/metrics.go#L77
is unable to GET the root credentials Secret as follows
https://github.com/openshift/cloud-credential-operator/blob/77a68ad01e75162bfa04097b22f80d305c192439/pkg/operator/metrics/metrics.go#L184
This is because above client is backed by a cache which only contains Secrets requested by other components but not the root credentials Secret, see
https://github.com/openshift/cloud-credential-operator/blob/77a68ad01e75162bfa04097b22f80d305c192439/pkg/cmd/operator/cmd.go#L164-L168

OCPBUGS-26488: Use live client for metrics

---

pkg/operator/metrics/metrics.go
pkg/operator/metrics/metrics_test.go

Client-side throttling was observed after switching to the live client in the metrics controller in #645. 
This PR:
- Adds a (cached) root client to the Calculator struct for querying the root credential only. 
- Switches back to the default (cached) client (i.e. `mgr.GetClient()`) for querying anything else.

OCPBUGS-27445: Use cached clients to avoid client side throttling

---

pkg/operator/metrics/metrics.go
pkg/operator/metrics/metrics_test.go

Report `manualpodidentity` instead of plain `manual` mode in the `cco_credentials_mode` metric when using Azure Workload Identity.

OCPBUGS-27446: Report manualpodidentity mode in metrics when using Azure Workload Identity

---

docs/metrics.md

Revise `metrics.md` to represent the current status:
- Add (mention) the `cco_credentials_mode` metric
- Update extra controller-runtime metrics

NO-JIRA: Keep metrics.md up-to-date

---

manifests/03-deployment.yaml

All openshift operators must include FallbackToLogsOnError to ease debugging.

OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

---

bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
manifests/0000_03_cloud-credential-operator_01_crd.yaml
manifests/0000_90_cloud-credential-operator_03_alertrules.yaml
pkg/apis/cloudcredential/v1/types_credentialsrequest.go
pkg/assets/bootstrap/bindata.go

Fix a few user-facing typos:
- in alert descriptions which are visible in the console
- in the description for `credentialsrequests.status.lastSyncCloudCredsSecretResourceVersion`

NO-JIRA: Fix user-facing typos

---

pkg/operator/secretannotator/aws/reconciler_test.go
pkg/operator/utils/aws/utils.go
pkg/operator/utils/utils.go

This PR:
- Fixes `LoadInfrastructureRegion` so it won't panic when being called on a non-AWS cluster (this is possible, see the attached card for details)
- Increase unit test coverage for the `secretannotator` controller
- Remove (another) `LoadInfrastructureRegion` which is no longer used

OCPBUGS-28535: stop LoadInfrastructureRegion from panicking when being called on a non-AWS cluster

---

pkg/cmd/provisioning/aws/create_identity_provider.go

Supporting proxy environment variables in ccoctl when creating aws identity provider with "private bucket", using CloudFront as OIDC endpoint.
Changes:
Tested scenarios/checklist:
Follow up:
- Bug report: https://issues.redhat.com/browse/OCPBUGS-27214
- Slack thread: https://redhat-internal.slack.com/archives/CE3ETN3J8/p1703762408695639

OCPBUGS-27214: ccoctl - use proxy when validating CloudFront URL

---

pkg/operator/status/status_controller.go

Previously the status controller erroneously:
- watches all ClusterOperators. 
- enqueues ClusterOperator/XXX instead of CloudCredential/cluster when informed by ClusterOperator-related events
This PR restricts the watch to ClusterOperator/cloud-credential and make sure the EventHandler always enqueues the same namespaced name (i.e. CloudCredential/cluster). 
See the comment section of the attached JIRA card for a comparison of metrics pre vs post bug fix.

OCPBUGS-28388: Fix the ClusterOperator watch of the status controller

---

hack/update-codegen.sh

The following issues are found on update-codegen.sh:
- On MacOS, `sed` interprets the string following `-i` as the `extension` passed to this flag, resulting in the following:
```shell
$ ./hack/update-codegen.sh
...
+ sed -i 's,^exec \(".*/generate-internal-groups.sh"\),bash \1,g' ./vendor/k8s.io/code-generator/generate-groups.sh
sed: 1: "./vendor/k8s.io/code-ge ...": invalid command code .
```
- Two traps could be set on the same signal (EXIT)
This PR:
- Use gsed (aka gnu-sed) for MacOS, sed otherwise. Also see: https://github.com/openshift/hive/pull/2183. 
- Aggregate all cleanup logics into the `cleanup` function so we end up with one single trap

NO-JIRA: Fix update-codegen.sh

---

pkg/aws/actuator/actuator.go
pkg/azure/actuator.go
pkg/gcp/actuator/actuator.go
pkg/kubevirt/actuator.go
pkg/openstack/actuator.go
pkg/operator/utils/utils.go
pkg/operator/utils/utils_test.go
pkg/ovirt/actuator.go
pkg/vsphere/actuator/actuator.go

After adding granular permissions to the GCP platform in 4.15, new permission are required on the root credential service account. The GCP platform in mint mode now requires the upgradeable annotation to upgrade from 4.14.x to a newer minor version such as 4.15.0.
This PR should only be applied to 4.14.

OCPBUGS-28231: Guard upgrading GCP from 4.14 to 4.15 without RoleAdmin permissions

---

pkg/aws/utils.go

The `HeadBucket` API call requires `s3:ListBucket` instead [1]
[1] https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html

OCPBUGS-31678: aws: remove non-existent permission

---

Dockerfile

This change adds cloud-credential-operator and ccoctl binaries for RHEL8 and RHEL9 builds, defaulting to RHEL9.

OCPBUGS-31290: Add binaries for RHEL8 and RHEL9, defaulting to RHEL9

---

Dockerfile

Previously we updated the Dockerfile to default to RHEL9 ccoctl binary. However, in order to remain consistent with prior behavior, we should instead default to the RHEL8 binary.

OCPBUGS-31290: Dockerfile should keep prior rhel8 behavior for ccoctl default

---

docs/azure_workload_identity.md

Update the Azure workload identity migration steps to utilize the oc adm extract --included option to select the proper credentialRequests for the cluster as opposed to trying to determine and use a release image.

OCPBUGS-33621: docs: Azure WI migration to extract only the credentialRequests needed by the cluster.

---

pkg/aws/actuator/actuator.go

When the operator in manual STS mode is attempting to reconcile a credentialRequest, it should not be throwing errors for credentialRequests that do not have awsSTSIAMRoleARN. Instead, it should be quietly ignoring them as they are not configured to be reconciled with STS.

OCPBUGS-33566: AWS STS should not error when a credentailsRequest does not have awsSTSIAMRoleARN

---

.snyk

SNYK is misreporting a vulnerability in go-client because it thinks we need v1.17 or higher. However, k8s numbering changed after v1.17 to v0.xx and so SNYK calculates v0.30.2 as less than v1.17.

OCPBUGS-37334: SNYK ignore go-client misreporting

---

pkg/cmd/operator/cmd.go

Prior to this change, the operator listed all of the secrets in every namespace using a single list call. The results were then used to determine if the operator can limit the secrets it is watching by label. Unfortunately, when there is a huge number of secrets, the kube API may timeout prior to returning the list.
This change modifies the behavior to pull the list in smaller batches to avoid reaching the timeout.

OCPBUGS-39531: List secrets in batches to avoid api timeout

---

bindata/v4.1.0/gcp-pod-identity-webhook/deployment.yaml
bindata/v4.1.0/gcp-pod-identity-webhook/mutatingwebhook.yaml
manifests/03-deployment.yaml
manifests/image-references
pkg/assets/v410_00_assets/bindata.go
pkg/operator/podidentity/gcppodidentitywebhook.go
pkg/operator/podidentity/podidentitywebhook_controller.go

This change adds the GCP Workload Identity Webhook when the cluster platform is GCP. The cloud-credential-operator ensures the deployment, pods, and mutating webhook exists.

CCO-571: Add GCP pod identity webhook

---

pkg/aws/actuator/actuator.go
pkg/azure/actuator.go
pkg/gcp/actuator/actuator.go
pkg/kubevirt/actuator.go
pkg/openstack/actuator.go
pkg/operator/credentialsrequest/actuator/actuator.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/ovirt/actuator.go
pkg/vsphere/actuator/actuator.go

Prior to this change, all platforms attempted to reconcile credentials
when in manual mode as if they were in mint mode. At one point, a per
platform featuregate happened to limit which ones were attempting to do
so. However, once the featuregate was removed, there was no further
logic to limit this.
This change adds a function to the actuator in order to enable each
platform to decide for itself if time token credentials are supported in
addition to determining if they are configured. This ensures each
platform only attempts to sync in manual mode if it already has the
logic to do so.
The following platforms have timed token credentials enabled:
AWS, Azure, GCP

OCPBUGS-36644: Only attempt timed token credentials on supported platforms.

---

pkg/aws/actuator/actuator.go
pkg/azure/actuator.go
pkg/gcp/actuator/actuator.go
pkg/kubevirt/actuator.go
pkg/openstack/actuator.go
pkg/operator/credentialsrequest/actuator/actuator.go
pkg/operator/credentialsrequest/credentialsrequest_controller.go
pkg/ovirt/actuator.go
pkg/vsphere/actuator/actuator.go

Prior to this change, all platforms attempted to reconcile credentials
when in manual mode as if they were in mint mode. At one point, a per
platform featuregate happened to limit which ones were attempting to do
so. However, once the featuregate was removed, there was no further
logic to limit this.
This change adds a function to the actuator in order to enable each
platform to decide for itself if time token credentials are supported in
addition to determining if they are configured. This ensures each
platform only attempts to sync in manual mode if it already has the
logic to do so.
The following platforms have timed token credentials enabled:
AWS, Azure

OCPBUGS-43645: Only attempt timed token credentials on supported platforms.

---

bindata/v4.1.0/gcp-pod-identity-webhook/deployment.yaml
bindata/v4.1.0/gcp-pod-identity-webhook/mutatingwebhook.yaml
manifests/03-deployment.yaml
manifests/image-references
pkg/assets/v410_00_assets/bindata.go
pkg/operator/podidentity/gcppodidentitywebhook.go
pkg/operator/podidentity/podidentitywebhook_controller.go

This change adds the GCP Workload Identity Webhook when the cluster platform is GCP. The cloud-credential-operator ensures the deployment, pods, and mutating webhook exists.

OCPBUGS-44123: Add GCP pod identity webhook

---

pkg/cmd/provisioning/azure/create_managed_identities.go
pkg/cmd/provisioning/gcp/create_service_accounts.go
pkg/cmd/provisioning/gcp/create_workload_identity_provider.go

The ccoct gcp create functions occassionaly fail when recently created resources have not yet replicated in the cloud. This change adds retry functionality to increase success rate when this happens.

OCPBUGS-44933: Add retry to ccoctl gcp create functions

---

pkg/cmd/provisioning/aws/create_identity_provider.go

Proposed fix for https://github.com/openshift/cloud-credential-operator/issues/761

NO-JIRA: Fix JSON for 07-block-public-access-to-oidc-bucket.json

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
pkg/assets/v410_00_assets/bindata.go
pkg/operator/podidentity/awspodidentitywebhook.go
pkg/operator/podidentity/azurepodidentitywebhook.go
pkg/operator/podidentity/gcppodidentitywebhook.go
pkg/operator/podidentity/podidentitywebhook_controller.go
pkg/operator/podidentity/podidentitywebhook_controller_test.go

AWS SDK Go Client v2 (v1 approaching EOL soon) does not allow STS sessions to authenticate without a valid AWS region set in the environment due to STS regional endpoints.
https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html#:~:text=SDK%20for%20Go%20V2%20(1.x)
The pod identity webhook binary injects the region only when the `--aws-default-region` flag is added. This is required for clients to continue authenticating with STS and avoid errors:
```
get identity: get credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region
```

OCPBUGS-41727: Add AWS region to aws-pod-identity-webhook

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
pkg/assets/v410_00_assets/bindata.go
pkg/operator/podidentity/awspodidentitywebhook.go
pkg/operator/podidentity/azurepodidentitywebhook.go
pkg/operator/podidentity/gcppodidentitywebhook.go
pkg/operator/podidentity/podidentitywebhook_controller.go
pkg/operator/podidentity/podidentitywebhook_controller_test.go

Manual cherry-pick of https://github.com/openshift/cloud-credential-operator/pull/798 as bot cherry-picking automation failed to apply due to minor conflicts.

[release-4.17] OCPBUGS-45938: Add AWS region to aws-pod-identity-webhook

---

pkg/operator/utils/utils.go

`status has changed, updating` shows that *something* is changing. But without a diff, it's hard to figure out what.  For example in [this recent CI run][1]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cloud-credential-operator/789/pull-ci-openshift-cloud-credential-operator-master-e2e-aws-manual-oidc/1864768460005838848/artifacts/e2e-aws-manual-oidc/gather-extra/artifacts/pods/openshift-cloud-credential-operator_cloud-credential-operator-64bcbb54cc-vzs5s_cloud-credential-operator.log | grep -1 ingress | tail -n13
--
time="2024-12-05T21:44:49Z" level=info msg="status has changed, updating" controller=credreq cr=openshift-cloud-credential-operator/aws-ebs-csi-driver-operator …
```

CCO-626: pkg/operator/utils: Log diff on CredentialsRequest status change

---

docs/rotate-oidc-key.md

Previously, the rotate oidc key documentation assumed the CLUSTER_ID has exactly 6 random characters appended to the end, including the hyphen. This change modifies it to instead use glob to remove any number of characters.

NO-JIRA: docs: rotate oidc key to use less opinionated CLUSTER_NAME

---

pkg/cmd/provisioning/aws/create-iam-roles.go
pkg/cmd/provisioning/aws/create_all.go

As per title, enable `--dry-run` when generating all AWS assets by running `ccoctl aws create-all`.
The change should be quite straightforward as the vast majority of the code is there, already implemented.
The sole relevant change is in `func getIssuerURLFromIdentityProvider`.

NO-JIRA: Add dry-run on aws create-all command

---

bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
bindata/v4.1.0/azure-pod-identity-webhook/deployment.yaml
bindata/v4.1.0/gcp-pod-identity-webhook/deployment.yaml
manifests/03-deployment.yaml
pkg/assets/v410_00_assets/bindata.go

The readOnlyRootFilesystem is now explicitly set to True on all containers. In order to for this to work on the cloud-credential-operator container, the tls-ca-bundle.pem mount being reverted to the default location.

CCO-647:  Enable readOnlyRootFilesystem on all containers

---

README.md
pkg/openstack/actuator.go
pkg/openstack/utils.go
pkg/operator/secretannotator/openstack/reconciler.go

If a CA bundle is required to talk to your OpenStack then obviously all services that talk to the cloud need to have both credentials and said bundle. Currently, these users can get their credentials via cloud credential operator, but they need to source their CA bundle from elsewhere (typically by extracting it from the cloud controller manager's configuration). This makes configuration of services more complicated than necessary.
Begin the resolution of the issue by allowing users (i.e. the Installer) to store the CA bundle in their root secret and dole this out to anyone who asks for it via a `CredentialsRequest`. Follow-up changes will be needed in places like the Installer and csi-operator to start setting/consuming this.

OSASINFRA-3657: Add support for storing OpenStack CA bundles

---

pkg/aws/actuator/actuator.go
pkg/aws/actuator/actuator_test.go

When the controller fails to create an STS secret, it doesn't surface the error generated by the k8s client.
The error message is instead quite generic and difficult to troubleshoot:
```
time="2025-03-10T08:58:38Z" level=error msg="error syncing credentials: error syncing creds in mint-mode: error processing secret" controller=credreq cr=openshift-cloud-credential-operator/cluster-init secret=ci/cluster-init-cloud-credentials
```

NO-JIRA: Report the error when syncing STS secrets

---

pkg/cmd/render/render.go

Previously, the static pod on the bootstrap machine was not aware of the
cluster-wide proxy configuration. This caused the static pod to be
unable to reach sites that were not allowed directly from the bootstrap
host. This caused installation failure in Mint and Passthrough mode as
the bootstrap process depends on some credentials being populated.
This change injects the proxy env variables into the static pod manifest
when rendered. It also mounts the ca-trust from the bootstrap host into
the pod. This enables the cloud-credential-operator binary to use the
proxy as configured in the environment variables on the static pod.
Previously, the render command used string templates to generate some
manifests. This made it difficult to modify the values, forcing all
changes to adhere to the …

OCPBUGS-53429: Render: configure proxy on bootstrap static pod

---

pkg/operator/secretannotator/openstack/reconciler.go
pkg/operator/secretannotator/openstack/reconciler_test.go

In #780, we added support for syncing CA bundles from the root credential secret to the generated credential secrets when running on OpenStack clouds. This is a big improvement for OpenShift developers, since it hugely simplifies how we obtain these in other operators and components and removes the need for a number of controllers. However, as things stand, it doesn't help users as it introduces a second place that they must consider when rotating credentials.
Long-term, we would like to remove the CA bundle from the cloud-providers config map. Doing so requires some rework of CCCMO as well as investigation into potential issues caused by CCMs role in early stage bootstrapping. This isn't going to happen in OpenShift 4.19, so for now we opt to leave the current documentation around cert …

OCPBUGS-55777: Sync OpenStack CA Bundles from legacy location

---

pkg/operator/secretannotator/vsphere/reconciler.go
pkg/operator/utils/errorscrub_test.go

Prior to this chance, some uses of fmt.Errorf passed a string variable as the one and only parameter. Starting with go v1.24, this throws an error when running go test.
This change modifies those cases to use a string constant the first variable configured to inject the string variable as the second parameter. This resolves the go test error.

OCPBUGS-57349: Use constant for first parameter of fmt.Errorf

---

Makefile

make update-go-dependencies to also update indirects
exclude prism-go-client ([CCO-643](https://issues.redhat.com//browse/CCO-643))
exclude msgraph-sdk-go ([CCO-644](https://issues.redhat.com//browse/CCO-644))

CCO-649: make update-go-dependencies to also update indirects

---

pkg/cmd/provisioning/azure/create_managed_identities.go
pkg/cmd/provisioning/azure/create_oidc_issuer.go
pkg/cmd/provisioning/azure/create_oidc_issuer_test.go

Prior to this change, ccoctl always added the owned tag to the resource groups and storage accounts. This caused errors when the number of owned tags from multpiple clusters exceeded the maximum tag limit.
This change makes it so the owned tag is only added when a resource group or storage account is actually created. Any additional clusters using these resources will not attempt to add their own owned tag. This enables significantly more clusters to share the same resources without reaching the limit.

OCPBUGS-53454: ccoctl: only add owned tag to azure resources on create

---

pkg/cmd/provisioning/azure/create_all.go
pkg/cmd/provisioning/azure/create_managed_identities.go

This changes the dnszone-resource-group-name parameter to no longer be required. This enables private clusters where the dns zone does not exists without requiring an arbitrary resource group name.

OCPBUGS-34993: ccoctl azure dnszone-resource-group-name now optional

---

manifests/03-deployment.yaml

As we use `kubectl logs -n openshift-cloud-credential-operator  cloud-credential-operator-xxx`, we see the default container logs is kube-rbac-proxy, like :
```
Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, cloud-credential-operator
W0707 04:28:43.641266       1 deprecated.go:66] 
==== Removed Flag Warning ======================
logtostderr is removed in the k8s upstream and has no effect any more.
===============================================
I0707 04:28:43.641998       1 kube-rbac-proxy.go:233] Valid token audiences: 
I0707 04:28:43.642069       1 kube-rbac-proxy.go:347] Reading certificate files
I0707 04:28:43.642557       1 kube-rbac-proxy.go:395] Starting TCP socket on 0.0.0.0:8443
```
But most of the time we just care about the container cloud-credential-operator …

OCPBUGS-61475: set cloud-credential-operator as default-container

---

.snyk

The package golang.org/x/net/html is only used by ccoctl, which neither runs on the cluster nor has a web service.

OCPBUGS-55127: snyk to ignore SNYK-GOLANG-GOLANGORGXNETHTML-9572088

---

pkg/aws/client.go

During the migration to aws-ask-go-v2, the iam client endpoint was used to override the baseEndpoint for all of the services. This did not cause any issues in the operator because it does not use these clients. And, it did not cause any issues in the ccoctl binary because it does not override the endpoints. However, this is causing issues with other projects which include the relevant code.
This change removes the assignemnt of the overrides for the s3 and cf clients. This removes the ability to override the s3 and cf client endpoints. However, this is not currently an issue because they are not used in combination at this time. If either of these clients become needed in the future, or the ccoctl gains the ability to override the endpoints, then this functionality will need to be sorted …

OCPBUGS-62184: aws: remove endpoint overrides for s3 and cf clients
